/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Swellcloud API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
	DataTag,
	DefinedInitialDataOptions,
	DefinedUseQueryResult,
	QueryClient,
	QueryFunction,
	QueryKey,
	UndefinedInitialDataOptions,
	UseQueryOptions,
	UseQueryResult,
} from "@tanstack/react-query";

import type {
	GetChartV1ChartsVariableForecastHourGetParams,
	GetPointForecastV1PointGetParams,
	HTTPValidationError,
	ListChartsV1ChartsGetParams,
	WmtsProxyV1WmtsProxyZXYGetParams,
} from "./models";

/**
 * @summary Root
 */
export type rootGetResponse200 = {
	data: unknown;
	status: 200;
};

export type rootGetResponseSuccess = rootGetResponse200 & {
	headers: Headers;
};

export type rootGetResponse = rootGetResponseSuccess;

export const getRootGetUrl = () => {
	return "https://api.swellcloud.net/";
};

export const rootGet = async (
	options?: RequestInit,
): Promise<rootGetResponse> => {
	const res = await fetch(getRootGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: rootGetResponse["data"] = body ? JSON.parse(body) : {};
	return { data, status: res.status, headers: res.headers } as rootGetResponse;
};

export const getRootGetQueryKey = () => {
	return ["https://api.swellcloud.net/"] as const;
};

export const getRootGetQueryOptions = <
	TData = Awaited<ReturnType<typeof rootGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getRootGetQueryKey();

	const queryFn: QueryFunction<Awaited<ReturnType<typeof rootGet>>> = ({
		signal,
	}) => rootGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof rootGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type RootGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof rootGet>>
>;
export type RootGetQueryError = unknown;

export function useRootGet<
	TData = Awaited<ReturnType<typeof rootGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof rootGet>>,
					TError,
					Awaited<ReturnType<typeof rootGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootGet<
	TData = Awaited<ReturnType<typeof rootGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof rootGet>>,
					TError,
					Awaited<ReturnType<typeof rootGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useRootGet<
	TData = Awaited<ReturnType<typeof rootGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Root
 */

export function useRootGet<
	TData = Awaited<ReturnType<typeof rootGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<Awaited<ReturnType<typeof rootGet>>, TError, TData>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getRootGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Health Check
 */
export type healthCheckHealthGetResponse200 = {
	data: unknown;
	status: 200;
};

export type healthCheckHealthGetResponseSuccess =
	healthCheckHealthGetResponse200 & {
		headers: Headers;
	};

export type healthCheckHealthGetResponse = healthCheckHealthGetResponseSuccess;

export const getHealthCheckHealthGetUrl = () => {
	return "https://api.swellcloud.net/health";
};

export const healthCheckHealthGet = async (
	options?: RequestInit,
): Promise<healthCheckHealthGetResponse> => {
	const res = await fetch(getHealthCheckHealthGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: healthCheckHealthGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as healthCheckHealthGetResponse;
};

export const getHealthCheckHealthGetQueryKey = () => {
	return ["https://api.swellcloud.net/health"] as const;
};

export const getHealthCheckHealthGetQueryOptions = <
	TData = Awaited<ReturnType<typeof healthCheckHealthGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof healthCheckHealthGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getHealthCheckHealthGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof healthCheckHealthGet>>
	> = ({ signal }) => healthCheckHealthGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof healthCheckHealthGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type HealthCheckHealthGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof healthCheckHealthGet>>
>;
export type HealthCheckHealthGetQueryError = unknown;

export function useHealthCheckHealthGet<
	TData = Awaited<ReturnType<typeof healthCheckHealthGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof healthCheckHealthGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof healthCheckHealthGet>>,
					TError,
					Awaited<ReturnType<typeof healthCheckHealthGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheckHealthGet<
	TData = Awaited<ReturnType<typeof healthCheckHealthGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof healthCheckHealthGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof healthCheckHealthGet>>,
					TError,
					Awaited<ReturnType<typeof healthCheckHealthGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useHealthCheckHealthGet<
	TData = Awaited<ReturnType<typeof healthCheckHealthGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof healthCheckHealthGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Health Check
 */

export function useHealthCheckHealthGet<
	TData = Awaited<ReturnType<typeof healthCheckHealthGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof healthCheckHealthGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getHealthCheckHealthGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get CA certificate chain for ESP32 clients

Returns the PEM-encoded certificate chain suitable for use with
client.setCACert() on ESP32 devices. No API key required.

Available at /v1/ca.pem, /ca.pem, and /esp32/ca.pem
 * @summary Get Esp32 Ca
 */
export type getEsp32CaEsp32CaPemGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getEsp32CaEsp32CaPemGetResponseSuccess =
	getEsp32CaEsp32CaPemGetResponse200 & {
		headers: Headers;
	};

export type getEsp32CaEsp32CaPemGetResponse =
	getEsp32CaEsp32CaPemGetResponseSuccess;

export const getGetEsp32CaEsp32CaPemGetUrl = () => {
	return "https://api.swellcloud.net/esp32/ca.pem";
};

export const getEsp32CaEsp32CaPemGet = async (
	options?: RequestInit,
): Promise<getEsp32CaEsp32CaPemGetResponse> => {
	const res = await fetch(getGetEsp32CaEsp32CaPemGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getEsp32CaEsp32CaPemGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getEsp32CaEsp32CaPemGetResponse;
};

export const getGetEsp32CaEsp32CaPemGetQueryKey = () => {
	return ["https://api.swellcloud.net/esp32/ca.pem"] as const;
};

export const getGetEsp32CaEsp32CaPemGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetEsp32CaEsp32CaPemGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>
	> = ({ signal }) => getEsp32CaEsp32CaPemGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEsp32CaEsp32CaPemGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>
>;
export type GetEsp32CaEsp32CaPemGetQueryError = unknown;

export function useGetEsp32CaEsp32CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
					TError,
					Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEsp32CaEsp32CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
					TError,
					Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEsp32CaEsp32CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Esp32 Ca
 */

export function useGetEsp32CaEsp32CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaEsp32CaPemGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetEsp32CaEsp32CaPemGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get CA certificate chain for ESP32 clients

Returns the PEM-encoded certificate chain suitable for use with
client.setCACert() on ESP32 devices. No API key required.

Available at /v1/ca.pem, /ca.pem, and /esp32/ca.pem
 * @summary Get Esp32 Ca
 */
export type getEsp32CaCaPemGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getEsp32CaCaPemGetResponseSuccess =
	getEsp32CaCaPemGetResponse200 & {
		headers: Headers;
	};

export type getEsp32CaCaPemGetResponse = getEsp32CaCaPemGetResponseSuccess;

export const getGetEsp32CaCaPemGetUrl = () => {
	return "https://api.swellcloud.net/ca.pem";
};

export const getEsp32CaCaPemGet = async (
	options?: RequestInit,
): Promise<getEsp32CaCaPemGetResponse> => {
	const res = await fetch(getGetEsp32CaCaPemGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getEsp32CaCaPemGetResponse["data"] = body ? JSON.parse(body) : {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getEsp32CaCaPemGetResponse;
};

export const getGetEsp32CaCaPemGetQueryKey = () => {
	return ["https://api.swellcloud.net/ca.pem"] as const;
};

export const getGetEsp32CaCaPemGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetEsp32CaCaPemGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getEsp32CaCaPemGet>>
	> = ({ signal }) => getEsp32CaCaPemGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEsp32CaCaPemGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getEsp32CaCaPemGet>>
>;
export type GetEsp32CaCaPemGetQueryError = unknown;

export function useGetEsp32CaCaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
					TError,
					Awaited<ReturnType<typeof getEsp32CaCaPemGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEsp32CaCaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
					TError,
					Awaited<ReturnType<typeof getEsp32CaCaPemGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEsp32CaCaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Esp32 Ca
 */

export function useGetEsp32CaCaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaCaPemGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetEsp32CaCaPemGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get CA certificate chain for ESP32 clients

Returns the PEM-encoded certificate chain suitable for use with
client.setCACert() on ESP32 devices. No API key required.

Available at /v1/ca.pem, /ca.pem, and /esp32/ca.pem
 * @summary Get Esp32 Ca
 */
export type getEsp32CaV1CaPemGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getEsp32CaV1CaPemGetResponseSuccess =
	getEsp32CaV1CaPemGetResponse200 & {
		headers: Headers;
	};

export type getEsp32CaV1CaPemGetResponse = getEsp32CaV1CaPemGetResponseSuccess;

export const getGetEsp32CaV1CaPemGetUrl = () => {
	return "https://api.swellcloud.net/v1/ca.pem";
};

export const getEsp32CaV1CaPemGet = async (
	options?: RequestInit,
): Promise<getEsp32CaV1CaPemGetResponse> => {
	const res = await fetch(getGetEsp32CaV1CaPemGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getEsp32CaV1CaPemGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getEsp32CaV1CaPemGetResponse;
};

export const getGetEsp32CaV1CaPemGetQueryKey = () => {
	return ["https://api.swellcloud.net/v1/ca.pem"] as const;
};

export const getGetEsp32CaV1CaPemGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getGetEsp32CaV1CaPemGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>
	> = ({ signal }) => getEsp32CaV1CaPemGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetEsp32CaV1CaPemGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>
>;
export type GetEsp32CaV1CaPemGetQueryError = unknown;

export function useGetEsp32CaV1CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
					TError,
					Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEsp32CaV1CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
					TError,
					Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetEsp32CaV1CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Esp32 Ca
 */

export function useGetEsp32CaV1CaPemGet<
	TData = Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getEsp32CaV1CaPemGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetEsp32CaV1CaPemGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * List available wave models
 * @summary List Models
 */
export type listModelsV1ModelsGetResponse200 = {
	data: unknown;
	status: 200;
};

export type listModelsV1ModelsGetResponseSuccess =
	listModelsV1ModelsGetResponse200 & {
		headers: Headers;
	};

export type listModelsV1ModelsGetResponse =
	listModelsV1ModelsGetResponseSuccess;

export const getListModelsV1ModelsGetUrl = () => {
	return "https://api.swellcloud.net/v1/models";
};

export const listModelsV1ModelsGet = async (
	options?: RequestInit,
): Promise<listModelsV1ModelsGetResponse> => {
	const res = await fetch(getListModelsV1ModelsGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listModelsV1ModelsGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as listModelsV1ModelsGetResponse;
};

export const getListModelsV1ModelsGetQueryKey = () => {
	return ["https://api.swellcloud.net/v1/models"] as const;
};

export const getListModelsV1ModelsGetQueryOptions = <
	TData = Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey = queryOptions?.queryKey ?? getListModelsV1ModelsGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof listModelsV1ModelsGet>>
	> = ({ signal }) => listModelsV1ModelsGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListModelsV1ModelsGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof listModelsV1ModelsGet>>
>;
export type ListModelsV1ModelsGetQueryError = unknown;

export function useListModelsV1ModelsGet<
	TData = Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
					TError,
					Awaited<ReturnType<typeof listModelsV1ModelsGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListModelsV1ModelsGet<
	TData = Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
					TError,
					Awaited<ReturnType<typeof listModelsV1ModelsGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListModelsV1ModelsGet<
	TData = Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Models
 */

export function useListModelsV1ModelsGet<
	TData = Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listModelsV1ModelsGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListModelsV1ModelsGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * List available forecast chart images

Returns metadata about available charts including:
- Variable types (hs = wave height, tp = wave period)
- Forecast hours available
- Base run information
- File paths
 * @summary List Charts
 */
export type listChartsV1ChartsGetResponse200 = {
	data: unknown;
	status: 200;
};

export type listChartsV1ChartsGetResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type listChartsV1ChartsGetResponseSuccess =
	listChartsV1ChartsGetResponse200 & {
		headers: Headers;
	};
export type listChartsV1ChartsGetResponseError =
	listChartsV1ChartsGetResponse422 & {
		headers: Headers;
	};

export type listChartsV1ChartsGetResponse =
	| listChartsV1ChartsGetResponseSuccess
	| listChartsV1ChartsGetResponseError;

export const getListChartsV1ChartsGetUrl = (
	params?: ListChartsV1ChartsGetParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://api.swellcloud.net/v1/charts?${stringifiedParams}`
		: "https://api.swellcloud.net/v1/charts";
};

export const listChartsV1ChartsGet = async (
	params?: ListChartsV1ChartsGetParams,
	options?: RequestInit,
): Promise<listChartsV1ChartsGetResponse> => {
	const res = await fetch(getListChartsV1ChartsGetUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: listChartsV1ChartsGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as listChartsV1ChartsGetResponse;
};

export const getListChartsV1ChartsGetQueryKey = (
	params?: ListChartsV1ChartsGetParams,
) => {
	return [
		"https://api.swellcloud.net/v1/charts",
		...(params ? [params] : []),
	] as const;
};

export const getListChartsV1ChartsGetQueryOptions = <
	TData = Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
	TError = HTTPValidationError,
>(
	params?: ListChartsV1ChartsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getListChartsV1ChartsGetQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof listChartsV1ChartsGet>>
	> = ({ signal }) =>
		listChartsV1ChartsGet(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListChartsV1ChartsGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof listChartsV1ChartsGet>>
>;
export type ListChartsV1ChartsGetQueryError = HTTPValidationError;

export function useListChartsV1ChartsGet<
	TData = Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
	TError = HTTPValidationError,
>(
	params: undefined | ListChartsV1ChartsGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
					TError,
					Awaited<ReturnType<typeof listChartsV1ChartsGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListChartsV1ChartsGet<
	TData = Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
	TError = HTTPValidationError,
>(
	params?: ListChartsV1ChartsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
					TError,
					Awaited<ReturnType<typeof listChartsV1ChartsGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useListChartsV1ChartsGet<
	TData = Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
	TError = HTTPValidationError,
>(
	params?: ListChartsV1ChartsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary List Charts
 */

export function useListChartsV1ChartsGet<
	TData = Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
	TError = HTTPValidationError,
>(
	params?: ListChartsV1ChartsGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof listChartsV1ChartsGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getListChartsV1ChartsGetQueryOptions(params, options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get a specific forecast chart image

Parameters:
- variable: 'hs' (wave height) or 'tp' (wave period)
- forecast_hour: Forecast hour (e.g., 3, 6, 9, 12, ...)
- format: 'png' or 'svg'

Returns the chart image file
 * @summary Get Chart
 */
export type getChartV1ChartsVariableForecastHourGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getChartV1ChartsVariableForecastHourGetResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getChartV1ChartsVariableForecastHourGetResponseSuccess =
	getChartV1ChartsVariableForecastHourGetResponse200 & {
		headers: Headers;
	};
export type getChartV1ChartsVariableForecastHourGetResponseError =
	getChartV1ChartsVariableForecastHourGetResponse422 & {
		headers: Headers;
	};

export type getChartV1ChartsVariableForecastHourGetResponse =
	| getChartV1ChartsVariableForecastHourGetResponseSuccess
	| getChartV1ChartsVariableForecastHourGetResponseError;

export const getGetChartV1ChartsVariableForecastHourGetUrl = (
	variable: string,
	forecastHour: number,
	params?: GetChartV1ChartsVariableForecastHourGetParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://api.swellcloud.net/v1/charts/${variable}/${forecastHour}?${stringifiedParams}`
		: `https://api.swellcloud.net/v1/charts/${variable}/${forecastHour}`;
};

export const getChartV1ChartsVariableForecastHourGet = async (
	variable: string,
	forecastHour: number,
	params?: GetChartV1ChartsVariableForecastHourGetParams,
	options?: RequestInit,
): Promise<getChartV1ChartsVariableForecastHourGetResponse> => {
	const res = await fetch(
		getGetChartV1ChartsVariableForecastHourGetUrl(
			variable,
			forecastHour,
			params,
		),
		{
			...options,
			method: "GET",
		},
	);

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getChartV1ChartsVariableForecastHourGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getChartV1ChartsVariableForecastHourGetResponse;
};

export const getGetChartV1ChartsVariableForecastHourGetQueryKey = (
	variable?: string,
	forecastHour?: number,
	params?: GetChartV1ChartsVariableForecastHourGetParams,
) => {
	return [
		`https://api.swellcloud.net/v1/charts/${variable}/${forecastHour}`,
		...(params ? [params] : []),
	] as const;
};

export const getGetChartV1ChartsVariableForecastHourGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
	TError = HTTPValidationError,
>(
	variable: string,
	forecastHour: number,
	params?: GetChartV1ChartsVariableForecastHourGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getGetChartV1ChartsVariableForecastHourGetQueryKey(
			variable,
			forecastHour,
			params,
		);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>
	> = ({ signal }) =>
		getChartV1ChartsVariableForecastHourGet(variable, forecastHour, params, {
			signal,
			...fetchOptions,
		});

	return {
		queryKey,
		queryFn,
		enabled: !!(variable && forecastHour),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChartV1ChartsVariableForecastHourGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>
>;
export type GetChartV1ChartsVariableForecastHourGetQueryError =
	HTTPValidationError;

export function useGetChartV1ChartsVariableForecastHourGet<
	TData = Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
	TError = HTTPValidationError,
>(
	variable: string,
	forecastHour: number,
	params: undefined | GetChartV1ChartsVariableForecastHourGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
					TError,
					Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChartV1ChartsVariableForecastHourGet<
	TData = Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
	TError = HTTPValidationError,
>(
	variable: string,
	forecastHour: number,
	params?: GetChartV1ChartsVariableForecastHourGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
					TError,
					Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChartV1ChartsVariableForecastHourGet<
	TData = Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
	TError = HTTPValidationError,
>(
	variable: string,
	forecastHour: number,
	params?: GetChartV1ChartsVariableForecastHourGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Chart
 */

export function useGetChartV1ChartsVariableForecastHourGet<
	TData = Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
	TError = HTTPValidationError,
>(
	variable: string,
	forecastHour: number,
	params?: GetChartV1ChartsVariableForecastHourGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartV1ChartsVariableForecastHourGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetChartV1ChartsVariableForecastHourGetQueryOptions(
		variable,
		forecastHour,
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get metadata about the chart generation run

Returns information about when charts were last generated
 * @summary Get Charts Metadata
 */
export type getChartsMetadataV1ChartsMetadataGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getChartsMetadataV1ChartsMetadataGetResponseSuccess =
	getChartsMetadataV1ChartsMetadataGetResponse200 & {
		headers: Headers;
	};

export type getChartsMetadataV1ChartsMetadataGetResponse =
	getChartsMetadataV1ChartsMetadataGetResponseSuccess;

export const getGetChartsMetadataV1ChartsMetadataGetUrl = () => {
	return "https://api.swellcloud.net/v1/charts/metadata";
};

export const getChartsMetadataV1ChartsMetadataGet = async (
	options?: RequestInit,
): Promise<getChartsMetadataV1ChartsMetadataGetResponse> => {
	const res = await fetch(getGetChartsMetadataV1ChartsMetadataGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getChartsMetadataV1ChartsMetadataGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getChartsMetadataV1ChartsMetadataGetResponse;
};

export const getGetChartsMetadataV1ChartsMetadataGetQueryKey = () => {
	return ["https://api.swellcloud.net/v1/charts/metadata"] as const;
};

export const getGetChartsMetadataV1ChartsMetadataGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetChartsMetadataV1ChartsMetadataGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>
	> = ({ signal }) =>
		getChartsMetadataV1ChartsMetadataGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetChartsMetadataV1ChartsMetadataGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>
>;
export type GetChartsMetadataV1ChartsMetadataGetQueryError = unknown;

export function useGetChartsMetadataV1ChartsMetadataGet<
	TData = Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
					TError,
					Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChartsMetadataV1ChartsMetadataGet<
	TData = Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
					TError,
					Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetChartsMetadataV1ChartsMetadataGet<
	TData = Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Charts Metadata
 */

export function useGetChartsMetadataV1ChartsMetadataGet<
	TData = Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getChartsMetadataV1ChartsMetadataGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getGetChartsMetadataV1ChartsMetadataGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get vector field data for particle animation

Args:
    hour: Forecast hour (e.g., "003", "006", "012")

Returns:
    JSON file with vector field data (u, v, energy)
 * @summary Get Vector Field
 */
export type getVectorFieldV1VectorsHourGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getVectorFieldV1VectorsHourGetResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getVectorFieldV1VectorsHourGetResponseSuccess =
	getVectorFieldV1VectorsHourGetResponse200 & {
		headers: Headers;
	};
export type getVectorFieldV1VectorsHourGetResponseError =
	getVectorFieldV1VectorsHourGetResponse422 & {
		headers: Headers;
	};

export type getVectorFieldV1VectorsHourGetResponse =
	| getVectorFieldV1VectorsHourGetResponseSuccess
	| getVectorFieldV1VectorsHourGetResponseError;

export const getGetVectorFieldV1VectorsHourGetUrl = (hour: string) => {
	return `https://api.swellcloud.net/v1/vectors/${hour}`;
};

export const getVectorFieldV1VectorsHourGet = async (
	hour: string,
	options?: RequestInit,
): Promise<getVectorFieldV1VectorsHourGetResponse> => {
	const res = await fetch(getGetVectorFieldV1VectorsHourGetUrl(hour), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getVectorFieldV1VectorsHourGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getVectorFieldV1VectorsHourGetResponse;
};

export const getGetVectorFieldV1VectorsHourGetQueryKey = (hour?: string) => {
	return [`https://api.swellcloud.net/v1/vectors/${hour}`] as const;
};

export const getGetVectorFieldV1VectorsHourGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
	TError = HTTPValidationError,
>(
	hour: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetVectorFieldV1VectorsHourGetQueryKey(hour);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>
	> = ({ signal }) =>
		getVectorFieldV1VectorsHourGet(hour, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!hour,
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetVectorFieldV1VectorsHourGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>
>;
export type GetVectorFieldV1VectorsHourGetQueryError = HTTPValidationError;

export function useGetVectorFieldV1VectorsHourGet<
	TData = Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
	TError = HTTPValidationError,
>(
	hour: string,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
					TError,
					Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVectorFieldV1VectorsHourGet<
	TData = Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
	TError = HTTPValidationError,
>(
	hour: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
					TError,
					Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetVectorFieldV1VectorsHourGet<
	TData = Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
	TError = HTTPValidationError,
>(
	hour: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Vector Field
 */

export function useGetVectorFieldV1VectorsHourGet<
	TData = Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
	TError = HTTPValidationError,
>(
	hour: string,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getVectorFieldV1VectorsHourGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetVectorFieldV1VectorsHourGetQueryOptions(
		hour,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Proxy WMTS GetCapabilities request to Copernicus Marine Service

Returns:
    XML GetCapabilities document
 * @summary Wmts Capabilities
 */
export type wmtsCapabilitiesV1WmtsCapabilitiesGetResponse200 = {
	data: unknown;
	status: 200;
};

export type wmtsCapabilitiesV1WmtsCapabilitiesGetResponseSuccess =
	wmtsCapabilitiesV1WmtsCapabilitiesGetResponse200 & {
		headers: Headers;
	};

export type wmtsCapabilitiesV1WmtsCapabilitiesGetResponse =
	wmtsCapabilitiesV1WmtsCapabilitiesGetResponseSuccess;

export const getWmtsCapabilitiesV1WmtsCapabilitiesGetUrl = () => {
	return "https://api.swellcloud.net/v1/wmts-capabilities";
};

export const wmtsCapabilitiesV1WmtsCapabilitiesGet = async (
	options?: RequestInit,
): Promise<wmtsCapabilitiesV1WmtsCapabilitiesGetResponse> => {
	const res = await fetch(getWmtsCapabilitiesV1WmtsCapabilitiesGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: wmtsCapabilitiesV1WmtsCapabilitiesGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as wmtsCapabilitiesV1WmtsCapabilitiesGetResponse;
};

export const getWmtsCapabilitiesV1WmtsCapabilitiesGetQueryKey = () => {
	return ["https://api.swellcloud.net/v1/wmts-capabilities"] as const;
};

export const getWmtsCapabilitiesV1WmtsCapabilitiesGetQueryOptions = <
	TData = Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getWmtsCapabilitiesV1WmtsCapabilitiesGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>
	> = ({ signal }) =>
		wmtsCapabilitiesV1WmtsCapabilitiesGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WmtsCapabilitiesV1WmtsCapabilitiesGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>
>;
export type WmtsCapabilitiesV1WmtsCapabilitiesGetQueryError = unknown;

export function useWmtsCapabilitiesV1WmtsCapabilitiesGet<
	TData = Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
					TError,
					Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWmtsCapabilitiesV1WmtsCapabilitiesGet<
	TData = Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
					TError,
					Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWmtsCapabilitiesV1WmtsCapabilitiesGet<
	TData = Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Wmts Capabilities
 */

export function useWmtsCapabilitiesV1WmtsCapabilitiesGet<
	TData = Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsCapabilitiesV1WmtsCapabilitiesGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions =
		getWmtsCapabilitiesV1WmtsCapabilitiesGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Proxy WMTS tile requests to Copernicus Marine Service with authentication

Args:
    z: Zoom level
    x: Tile X coordinate
    y: Tile Y coordinate
    layer: Layer identifier (VHM0_SW1, VHM0_SW2, VHM0)
    time: Time in ISO8601 format (e.g., 2025-12-15T21:00:00.000Z)

Returns:
    PNG tile image
 * @summary Wmts Proxy
 */
export type wmtsProxyV1WmtsProxyZXYGetResponse200 = {
	data: unknown;
	status: 200;
};

export type wmtsProxyV1WmtsProxyZXYGetResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type wmtsProxyV1WmtsProxyZXYGetResponseSuccess =
	wmtsProxyV1WmtsProxyZXYGetResponse200 & {
		headers: Headers;
	};
export type wmtsProxyV1WmtsProxyZXYGetResponseError =
	wmtsProxyV1WmtsProxyZXYGetResponse422 & {
		headers: Headers;
	};

export type wmtsProxyV1WmtsProxyZXYGetResponse =
	| wmtsProxyV1WmtsProxyZXYGetResponseSuccess
	| wmtsProxyV1WmtsProxyZXYGetResponseError;

export const getWmtsProxyV1WmtsProxyZXYGetUrl = (
	z: number,
	x: number,
	y: number,
	params: WmtsProxyV1WmtsProxyZXYGetParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://api.swellcloud.net/v1/wmts-proxy/${z}/${x}/${y}?${stringifiedParams}`
		: `https://api.swellcloud.net/v1/wmts-proxy/${z}/${x}/${y}`;
};

export const wmtsProxyV1WmtsProxyZXYGet = async (
	z: number,
	x: number,
	y: number,
	params: WmtsProxyV1WmtsProxyZXYGetParams,
	options?: RequestInit,
): Promise<wmtsProxyV1WmtsProxyZXYGetResponse> => {
	const res = await fetch(getWmtsProxyV1WmtsProxyZXYGetUrl(z, x, y, params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: wmtsProxyV1WmtsProxyZXYGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as wmtsProxyV1WmtsProxyZXYGetResponse;
};

export const getWmtsProxyV1WmtsProxyZXYGetQueryKey = (
	z?: number,
	x?: number,
	y?: number,
	params?: WmtsProxyV1WmtsProxyZXYGetParams,
) => {
	return [
		`https://api.swellcloud.net/v1/wmts-proxy/${z}/${x}/${y}`,
		...(params ? [params] : []),
	] as const;
};

export const getWmtsProxyV1WmtsProxyZXYGetQueryOptions = <
	TData = Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
	TError = HTTPValidationError,
>(
	z: number,
	x: number,
	y: number,
	params: WmtsProxyV1WmtsProxyZXYGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ??
		getWmtsProxyV1WmtsProxyZXYGetQueryKey(z, x, y, params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>
	> = ({ signal }) =>
		wmtsProxyV1WmtsProxyZXYGet(z, x, y, params, { signal, ...fetchOptions });

	return {
		queryKey,
		queryFn,
		enabled: !!(z && x && y),
		...queryOptions,
	} as UseQueryOptions<
		Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WmtsProxyV1WmtsProxyZXYGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>
>;
export type WmtsProxyV1WmtsProxyZXYGetQueryError = HTTPValidationError;

export function useWmtsProxyV1WmtsProxyZXYGet<
	TData = Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
	TError = HTTPValidationError,
>(
	z: number,
	x: number,
	y: number,
	params: WmtsProxyV1WmtsProxyZXYGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
					TError,
					Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWmtsProxyV1WmtsProxyZXYGet<
	TData = Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
	TError = HTTPValidationError,
>(
	z: number,
	x: number,
	y: number,
	params: WmtsProxyV1WmtsProxyZXYGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
					TError,
					Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWmtsProxyV1WmtsProxyZXYGet<
	TData = Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
	TError = HTTPValidationError,
>(
	z: number,
	x: number,
	y: number,
	params: WmtsProxyV1WmtsProxyZXYGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Wmts Proxy
 */

export function useWmtsProxyV1WmtsProxyZXYGet<
	TData = Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
	TError = HTTPValidationError,
>(
	z: number,
	x: number,
	y: number,
	params: WmtsProxyV1WmtsProxyZXYGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof wmtsProxyV1WmtsProxyZXYGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getWmtsProxyV1WmtsProxyZXYGetQueryOptions(
		z,
		x,
		y,
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * @summary Get Point Forecast
 */
export type getPointForecastV1PointGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getPointForecastV1PointGetResponse422 = {
	data: HTTPValidationError;
	status: 422;
};

export type getPointForecastV1PointGetResponseSuccess =
	getPointForecastV1PointGetResponse200 & {
		headers: Headers;
	};
export type getPointForecastV1PointGetResponseError =
	getPointForecastV1PointGetResponse422 & {
		headers: Headers;
	};

export type getPointForecastV1PointGetResponse =
	| getPointForecastV1PointGetResponseSuccess
	| getPointForecastV1PointGetResponseError;

export const getGetPointForecastV1PointGetUrl = (
	params: GetPointForecastV1PointGetParams,
) => {
	const normalizedParams = new URLSearchParams();

	Object.entries(params || {}).forEach(([key, value]) => {
		if (value !== undefined) {
			normalizedParams.append(key, value === null ? "null" : value.toString());
		}
	});

	const stringifiedParams = normalizedParams.toString();

	return stringifiedParams.length > 0
		? `https://api.swellcloud.net/v1/point?${stringifiedParams}`
		: "https://api.swellcloud.net/v1/point";
};

export const getPointForecastV1PointGet = async (
	params: GetPointForecastV1PointGetParams,
	options?: RequestInit,
): Promise<getPointForecastV1PointGetResponse> => {
	const res = await fetch(getGetPointForecastV1PointGetUrl(params), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getPointForecastV1PointGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getPointForecastV1PointGetResponse;
};

export const getGetPointForecastV1PointGetQueryKey = (
	params?: GetPointForecastV1PointGetParams,
) => {
	return [
		"https://api.swellcloud.net/v1/point",
		...(params ? [params] : []),
	] as const;
};

export const getGetPointForecastV1PointGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
	TError = HTTPValidationError,
>(
	params: GetPointForecastV1PointGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetPointForecastV1PointGetQueryKey(params);

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getPointForecastV1PointGet>>
	> = ({ signal }) =>
		getPointForecastV1PointGet(params, { signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetPointForecastV1PointGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getPointForecastV1PointGet>>
>;
export type GetPointForecastV1PointGetQueryError = HTTPValidationError;

export function useGetPointForecastV1PointGet<
	TData = Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
	TError = HTTPValidationError,
>(
	params: GetPointForecastV1PointGetParams,
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
					TError,
					Awaited<ReturnType<typeof getPointForecastV1PointGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPointForecastV1PointGet<
	TData = Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
	TError = HTTPValidationError,
>(
	params: GetPointForecastV1PointGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
					TError,
					Awaited<ReturnType<typeof getPointForecastV1PointGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetPointForecastV1PointGet<
	TData = Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
	TError = HTTPValidationError,
>(
	params: GetPointForecastV1PointGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Point Forecast
 */

export function useGetPointForecastV1PointGet<
	TData = Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
	TError = HTTPValidationError,
>(
	params: GetPointForecastV1PointGetParams,
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getPointForecastV1PointGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetPointForecastV1PointGetQueryOptions(
		params,
		options,
	);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}

/**
 * Get API status including last successful model run and next forecast run times
 * @summary Get Api Status
 */
export type getApiStatusV1StatusGetResponse200 = {
	data: unknown;
	status: 200;
};

export type getApiStatusV1StatusGetResponseSuccess =
	getApiStatusV1StatusGetResponse200 & {
		headers: Headers;
	};

export type getApiStatusV1StatusGetResponse =
	getApiStatusV1StatusGetResponseSuccess;

export const getGetApiStatusV1StatusGetUrl = () => {
	return "https://api.swellcloud.net/v1/status";
};

export const getApiStatusV1StatusGet = async (
	options?: RequestInit,
): Promise<getApiStatusV1StatusGetResponse> => {
	const res = await fetch(getGetApiStatusV1StatusGetUrl(), {
		...options,
		method: "GET",
	});

	const body = [204, 205, 304].includes(res.status) ? null : await res.text();

	const data: getApiStatusV1StatusGetResponse["data"] = body
		? JSON.parse(body)
		: {};
	return {
		data,
		status: res.status,
		headers: res.headers,
	} as getApiStatusV1StatusGetResponse;
};

export const getGetApiStatusV1StatusGetQueryKey = () => {
	return ["https://api.swellcloud.net/v1/status"] as const;
};

export const getGetApiStatusV1StatusGetQueryOptions = <
	TData = Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
	TError = unknown,
>(options?: {
	query?: Partial<
		UseQueryOptions<
			Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
			TError,
			TData
		>
	>;
	fetch?: RequestInit;
}) => {
	const { query: queryOptions, fetch: fetchOptions } = options ?? {};

	const queryKey =
		queryOptions?.queryKey ?? getGetApiStatusV1StatusGetQueryKey();

	const queryFn: QueryFunction<
		Awaited<ReturnType<typeof getApiStatusV1StatusGet>>
	> = ({ signal }) => getApiStatusV1StatusGet({ signal, ...fetchOptions });

	return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
		Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
		TError,
		TData
	> & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetApiStatusV1StatusGetQueryResult = NonNullable<
	Awaited<ReturnType<typeof getApiStatusV1StatusGet>>
>;
export type GetApiStatusV1StatusGetQueryError = unknown;

export function useGetApiStatusV1StatusGet<
	TData = Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
	TError = unknown,
>(
	options: {
		query: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
				TError,
				TData
			>
		> &
			Pick<
				DefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
					TError,
					Awaited<ReturnType<typeof getApiStatusV1StatusGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiStatusV1StatusGet<
	TData = Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
				TError,
				TData
			>
		> &
			Pick<
				UndefinedInitialDataOptions<
					Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
					TError,
					Awaited<ReturnType<typeof getApiStatusV1StatusGet>>
				>,
				"initialData"
			>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetApiStatusV1StatusGet<
	TData = Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Api Status
 */

export function useGetApiStatusV1StatusGet<
	TData = Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
	TError = unknown,
>(
	options?: {
		query?: Partial<
			UseQueryOptions<
				Awaited<ReturnType<typeof getApiStatusV1StatusGet>>,
				TError,
				TData
			>
		>;
		fetch?: RequestInit;
	},
	queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
	queryKey: DataTag<QueryKey, TData, TError>;
} {
	const queryOptions = getGetApiStatusV1StatusGetQueryOptions(options);

	const query = useQuery(queryOptions, queryClient) as UseQueryResult<
		TData,
		TError
	> & { queryKey: DataTag<QueryKey, TData, TError> };

	query.queryKey = queryOptions.queryKey;

	return query;
}
