/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --env-interface CloudflareBindings` (hash: 1e774d52e13680439ab50ce2b9d4c11b)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
		durableNamespaces: "Chat" | "Whatsapp";
	}
	interface Env {
		KV: KVNamespace;
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
		ACCOUNT_ID: "fa192b38975cc1a093d7dc819afa0c64";
		AI_GATEWAY_ID: "default";
		GOOGLE_CLIENT_ID: "843872966928-4q8r4o4p52h90f52jpjotmmncgr5mrra.apps.googleusercontent.com";
		OPENAI_API_KEY: string;
		DEEPSEEK_API_KEY: string;
		CLOUDFLARE_API_TOKEN: string;
		GEMINI_API_KEY: string;
		BETTER_AUTH_SECRET: string;
		GOOGLE_CLIENT_SECRET: string;
		VAPID_PUBLIC_KEY: string;
		VAPID_PRIVATE_KEY: string;
		VAPID_SUBJECT: string;
		TWILIO_ACCOUNT_SID: string;
		TWILIO_API_KEY: string;
		TWILIO_API_SECRET: string;
		TWILIO_SERVICE_SID: string;
		Chat: DurableObjectNamespace<import("./workers/app").Chat>;
		Whatsapp: DurableObjectNamespace<import("./workers/app").Whatsapp>;
		DB: D1Database;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "VALUE_FROM_CLOUDFLARE" | "ACCOUNT_ID" | "AI_GATEWAY_ID" | "GOOGLE_CLIENT_ID" | "OPENAI_API_KEY" | "DEEPSEEK_API_KEY" | "CLOUDFLARE_API_TOKEN" | "GEMINI_API_KEY" | "BETTER_AUTH_SECRET" | "GOOGLE_CLIENT_SECRET" | "VAPID_PUBLIC_KEY" | "VAPID_PRIVATE_KEY" | "VAPID_SUBJECT" | "TWILIO_ACCOUNT_SID" | "TWILIO_API_KEY" | "TWILIO_API_SECRET" | "TWILIO_SERVICE_SID">> {}
}
