/* eslint-disable */
// Generated by Wrangler by running `wrangler types --no-include-runtime --env-interface CloudflareBindings` (hash: 4ec58cf8f37b9230b84173598ccf689c)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./workers/app");
		durableNamespaces: "Chat";
	}
	interface Env {
		KV: KVNamespace;
		VALUE_FROM_CLOUDFLARE: "Hello from Cloudflare";
		ACCOUNT_ID: "fa192b38975cc1a093d7dc819afa0c64";
		AI_GATEWAY_ID: "default";
		GOOGLE_CLIENT_ID: "843872966928-4q8r4o4p52h90f52jpjotmmncgr5mrra.apps.googleusercontent.com";
		MAILGUN_DOMAIN: "thestorybookcharactercompany.com";
		ENABLE_SWELL_CLOUD: "false";
		ENABLE_SURFLINE: "true";
		WAHA_SESSION_ID: "16195985494@c.us";
		IMAGE_PROVIDER: "gemini";
		ENVIRONMENT: string;
		OPENAI_API_KEY: string;
		DEEPSEEK_API_KEY: string;
		CLOUDFLARE_API_TOKEN: string;
		GEMINI_API_KEY: string;
		BETTER_AUTH_SECRET: string;
		GOOGLE_CLIENT_SECRET: string;
		VAPID_PUBLIC_KEY: string;
		VAPID_PRIVATE_KEY: string;
		VAPID_SUBJECT: string;
		TWILIO_ACCOUNT_SID: string;
		TWILIO_API_KEY: string;
		TWILIO_API_SECRET: string;
		TWILIO_AUTH_TOKEN: string;
		TWILIO_SERVICE_SID: string;
		TWILIO_EVENT_SYNC_ID: string;
		SWELL_CLOUD_API_KEY: string;
		WAHA_API_KEY: string;
		WHATSAPP_SWAGGER_PASSWORD: string;
		OPENROUTER_API_KEY: string;
		MAILGUN_API_KEY: string;
		Chat: DurableObjectNamespace<import("./workers/app").Chat>;
		PROFILE_IMAGES_BUCKET: R2Bucket;
		DB: D1Database;
		WHATSAPP_QUEUE: Queue;
	}
}
interface CloudflareBindings extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv
		extends StringifyValues<
			Pick<
				Cloudflare.Env,
				| "VALUE_FROM_CLOUDFLARE"
				| "ACCOUNT_ID"
				| "AI_GATEWAY_ID"
				| "GOOGLE_CLIENT_ID"
				| "MAILGUN_DOMAIN"
				| "ENABLE_SWELL_CLOUD"
				| "ENABLE_SURFLINE"
				| "WAHA_SESSION_ID"
				| "IMAGE_PROVIDER"
				| "ENVIRONMENT"
				| "OPENAI_API_KEY"
				| "DEEPSEEK_API_KEY"
				| "CLOUDFLARE_API_TOKEN"
				| "GEMINI_API_KEY"
				| "BETTER_AUTH_SECRET"
				| "GOOGLE_CLIENT_SECRET"
				| "VAPID_PUBLIC_KEY"
				| "VAPID_PRIVATE_KEY"
				| "VAPID_SUBJECT"
				| "TWILIO_ACCOUNT_SID"
				| "TWILIO_API_KEY"
				| "TWILIO_API_SECRET"
				| "TWILIO_AUTH_TOKEN"
				| "TWILIO_SERVICE_SID"
				| "TWILIO_EVENT_SYNC_ID"
				| "SWELL_CLOUD_API_KEY"
				| "WAHA_API_KEY"
				| "WHATSAPP_SWAGGER_PASSWORD"
				| "OPENROUTER_API_KEY"
				| "MAILGUN_API_KEY"
			>
		> {}
}
