/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Accounts
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { AccountsV1BulkConsentsItems } from './accountsV1BulkConsentsItems';

export interface AccountsV1BulkConsents {
  /**
   * A list of objects where each object represents the result of processing a `correlation_id`. Each object contains the following fields: `correlation_id`, a unique 32-character UUID that maps the response to the original request; `error_code`, an integer where 0 indicates success and any non-zero value represents an error; and `error_messages`, an array of strings describing specific validation errors encountered. If the request is successful, the error_messages array will be empty.
   * @nullable
   */
  items?: AccountsV1BulkConsentsItems;
}
