/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Accounts
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface AccountsV1Safelist {
	/**
	 * The unique string that we created to identify the SafeList resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^GN[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The phone number or phone number 1k prefix in SafeList.
	 * @nullable
	 */
	phone_number?: string | null;
}
