/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * DEPRECATED. Feedback on how to improve brand score
 */
export type BrandRegistrationsEnumBrandFeedback = typeof BrandRegistrationsEnumBrandFeedback[keyof typeof BrandRegistrationsEnumBrandFeedback];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BrandRegistrationsEnumBrandFeedback = {
  TAX_ID: 'TAX_ID',
  STOCK_SYMBOL: 'STOCK_SYMBOL',
  NONPROFIT: 'NONPROFIT',
  GOVERNMENT_ENTITY: 'GOVERNMENT_ENTITY',
  OTHERS: 'OTHERS',
} as const;
