/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Brand Registration status. One of "PENDING", "APPROVED", "FAILED", "IN_REVIEW", "DELETION_PENDING", "DELETION_FAILED", "SUSPENDED".
 */
export type BrandRegistrationsEnumStatus =
	(typeof BrandRegistrationsEnumStatus)[keyof typeof BrandRegistrationsEnumStatus];

export const BrandRegistrationsEnumStatus = {
	PENDING: "PENDING",
	APPROVED: "APPROVED",
	FAILED: "FAILED",
	IN_REVIEW: "IN_REVIEW",
	DELETION_PENDING: "DELETION_PENDING",
	DELETION_FAILED: "DELETION_FAILED",
	SUSPENDED: "SUSPENDED",
} as const;
