/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * When a brand is registered, TCR will attempt to verify the identity of the brand based on the supplied information.
 */
export type BrandRegistrationsEnumIdentityStatus =
	(typeof BrandRegistrationsEnumIdentityStatus)[keyof typeof BrandRegistrationsEnumIdentityStatus];

export const BrandRegistrationsEnumIdentityStatus = {
	SELF_DECLARED: "SELF_DECLARED",
	UNVERIFIED: "UNVERIFIED",
	VERIFIED: "VERIFIED",
	VETTED_VERIFIED: "VETTED_VERIFIED",
} as const;
