/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The third-party provider that has conducted the vetting. One of “CampaignVerify” (Campaign Verify tokens) or “AEGIS” (Secondary Vetting).
 */
export type BrandVettingEnumVettingProvider =
	(typeof BrandVettingEnumVettingProvider)[keyof typeof BrandVettingEnumVettingProvider];

export const BrandVettingEnumVettingProvider = {
	"campaign-verify": "campaign-verify",
	aegis: "aegis",
} as const;
