/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The routing target of the webhook. Can be ordinary or route internally to Flex
 */
export type ConfigurationWebhookEnumTarget = typeof ConfigurationWebhookEnumTarget[keyof typeof ConfigurationWebhookEnumTarget];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConfigurationWebhookEnumTarget = {
  webhook: 'webhook',
  flex: 'flex',
} as const;
