/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ConfigurationAddressEnumMethod =
	(typeof ConfigurationAddressEnumMethod)[keyof typeof ConfigurationAddressEnumMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConfigurationAddressEnumMethod = {
	get: "get",
	post: "post",
} as const;
