/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ConfigurationAddressEnumAutoCreationType =
	(typeof ConfigurationAddressEnumAutoCreationType)[keyof typeof ConfigurationAddressEnumAutoCreationType];

export const ConfigurationAddressEnumAutoCreationType = {
	webhook: "webhook",
	studio: "studio",
	default: "default",
} as const;
