/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Type of Address, value can be `whatsapp` or `sms`.
 */
export type ConfigurationAddressEnumType =
	(typeof ConfigurationAddressEnumType)[keyof typeof ConfigurationAddressEnumType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConfigurationAddressEnumType = {
	sms: "sms",
	whatsapp: "whatsapp",
	messenger: "messenger",
	gbm: "gbm",
	email: "email",
	rcs: "rcs",
	apple: "apple",
	chat: "chat",
} as const;
