/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The configuration of this webhook. Is defined based on target.
 * @nullable
 */
export type ConversationsV1ServiceServiceConversationServiceConversationScopedWebhookConfiguration =
	| unknown
	| null;
