/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ConversationParticipantEnumWebhookEnabledType =
	(typeof ConversationParticipantEnumWebhookEnabledType)[keyof typeof ConversationParticipantEnumWebhookEnabledType];

export const ConversationParticipantEnumWebhookEnabledType = {
	true: "true",
	false: "false",
} as const;
