/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationsV1ConversationConversationMessageDelivery } from "./conversationsV1ConversationConversationMessageDelivery";
import type { ConversationsV1ConversationConversationMessageLinks } from "./conversationsV1ConversationConversationMessageLinks";

export interface ConversationsV1ConversationConversationMessage {
	/**
	 * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this message.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) for this message.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^CH[0-9a-fA-F]{32}$
	 */
	conversation_sid?: string | null;
	/**
	 * A 34 character string that uniquely identifies this resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^IM[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/** The index of the message within the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource).  Indices may skip numbers, but will always be in order of when the message was received. */
	index?: number;
	/**
	 * The channel specific identifier of the message's author. Defaults to `system`.
	 * @nullable
	 */
	author?: string | null;
	/**
	 * The content of the message, can be up to 1,600 characters long.
	 * @nullable
	 */
	body?: string | null;
	/**
	 * An array of objects that describe the Message's media, if the message contains media. Each object contains these fields: `content_type` with the MIME type of the media, `filename` with the name of the media, `sid` with the SID of the Media resource, and `size` with the media object's file size in bytes. If the Message has no media, this value is `null`.
	 * @nullable
	 */
	media?: unknown[] | null;
	/**
	 * A string metadata field you can use to store any data you wish. The string value must contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will be returned.
	 * @nullable
	 */
	attributes?: string | null;
	/**
	 * The unique ID of messages's author participant. Null in case of `system` sent message.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MB[0-9a-fA-F]{32}$
	 */
	participant_sid?: string | null;
	/**
	 * The date that this resource was created.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date that this resource was last updated. `null` if the message has not been edited.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * An absolute API resource API URL for this message.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * An object that contains the summary of delivery statuses for the message to non-chat participants.
	 * @nullable
	 */
	delivery?: ConversationsV1ConversationConversationMessageDelivery;
	/**
	 * Contains an absolute API resource URL to access the delivery & read receipts of this message.
	 * @nullable
	 */
	links?: ConversationsV1ConversationConversationMessageLinks;
	/**
	 * The unique ID of the multi-channel [Rich Content](https://www.twilio.com/docs/content) template.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^HX[0-9a-fA-F]{32}$
	 */
	content_sid?: string | null;
}
