/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Contains an absolute API resource URL to access the push notifications configuration of this service.
 * @nullable
 */
export type ConversationsV1ServiceServiceConfigurationLinks = {
	[key: string]: unknown;
} | null;
