/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The message delivery status, can be `read`, `failed`, `delivered`, `undelivered`, `sent` or null.
 */
export type ConversationMessageReceiptEnumDeliveryStatus =
	(typeof ConversationMessageReceiptEnumDeliveryStatus)[keyof typeof ConversationMessageReceiptEnumDeliveryStatus];

export const ConversationMessageReceiptEnumDeliveryStatus = {
	read: "read",
	failed: "failed",
	delivered: "delivered",
	undelivered: "undelivered",
	sent: "sent",
} as const;
