/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationsV1ServiceServiceConfigurationLinks } from './conversationsV1ServiceServiceConfigurationLinks';

export interface ConversationsV1ServiceServiceConfiguration {
  /**
   * The unique string that we created to identify the Service configuration resource.
   * @minLength 34
   * @maxLength 34
   * @nullable
   * @pattern ^IS[0-9a-fA-F]{32}$
   */
  chat_service_sid?: string | null;
  /**
   * The conversation-level role assigned to a conversation creator when they join a new conversation. See [Conversation Role](https://www.twilio.com/docs/conversations/api/role-resource) for more info about roles.
   * @minLength 34
   * @maxLength 34
   * @nullable
   * @pattern ^RL[0-9a-fA-F]{32}$
   */
  default_conversation_creator_role_sid?: string | null;
  /**
   * The conversation-level role assigned to users when they are added to a conversation. See [Conversation Role](https://www.twilio.com/docs/conversations/api/role-resource) for more info about roles.
   * @minLength 34
   * @maxLength 34
   * @nullable
   * @pattern ^RL[0-9a-fA-F]{32}$
   */
  default_conversation_role_sid?: string | null;
  /**
   * The service-level role assigned to users when they are added to the service. See [Conversation Role](https://www.twilio.com/docs/conversations/api/role-resource) for more info about roles.
   * @minLength 34
   * @maxLength 34
   * @nullable
   * @pattern ^RL[0-9a-fA-F]{32}$
   */
  default_chat_service_role_sid?: string | null;
  /**
   * An absolute API resource URL for this service configuration.
   * @nullable
   */
  url?: string | null;
  /**
   * Contains an absolute API resource URL to access the push notifications configuration of this service.
   * @nullable
   */
  links?: ConversationsV1ServiceServiceConfigurationLinks;
  /**
   * Whether the [Reachability Indicator](https://www.twilio.com/docs/conversations/reachability) is enabled for this Conversations Service. The default is `false`.
   * @nullable
   */
  reachability_enabled?: boolean | null;
}
