/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Contains absolute API resource URLs to access conversations, users, roles, bindings and configuration of this service.
 * @nullable
 */
export type ConversationsV1ServiceLinks = { [key: string]: unknown } | null;
