/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The Push Notification configuration for being removed from a Conversation.
 * @nullable
 */
export type ConversationsV1ServiceServiceConfigurationServiceNotificationRemovedFromConversation =
	| unknown
	| null;
