/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Auto Creation configuration for the address.
 * @nullable
 */
export type ConversationsV1ConfigurationAddressAutoCreation = unknown | null;
