/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The routing target of the webhook. Can be ordinary or route internally to Flex
 */
export type ConversationWebhookEnumTarget =
	(typeof ConversationWebhookEnumTarget)[keyof typeof ConversationWebhookEnumTarget];

export const ConversationWebhookEnumTarget = {
	webhook: "webhook",
	flex: "flex",
} as const;
