/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * An object that contains the summary of delivery statuses for the message to non-chat participants.
 * @nullable
 */
export type ConversationsV1ConversationConversationMessageDelivery = unknown | null;
