/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Information about how this participant exchanges messages with the conversation. A JSON parameter consisting of type and address fields of the participant.
 * @nullable
 */
export type ConversationsV1ParticipantConversationParticipantMessagingBinding =
	| unknown
	| null;
