/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ConversationScopedWebhookEnumMethod =
	(typeof ConversationScopedWebhookEnumMethod)[keyof typeof ConversationScopedWebhookEnumMethod];

export const ConversationScopedWebhookEnumMethod = {
	get: "get",
	post: "post",
} as const;
