/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The HTTP method to be used when sending a webhook request.
 */
export type ConversationWebhookEnumMethod =
	(typeof ConversationWebhookEnumMethod)[keyof typeof ConversationWebhookEnumMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationWebhookEnumMethod = {
	GET: "GET",
	POST: "POST",
} as const;
