import type { ConversationsV1ParticipantConversationConversationTimers } from "./conversationsV1ParticipantConversationConversationTimers";
import type { ConversationsV1ParticipantConversationLinks } from "./conversationsV1ParticipantConversationLinks";
/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationsV1ParticipantConversationParticipantMessagingBinding } from "./conversationsV1ParticipantConversationParticipantMessagingBinding";
import type { ParticipantConversationEnumState } from "./participantConversationEnumState";

export interface ConversationsV1ParticipantConversation {
	/**
	 * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this conversation.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The unique ID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) this conversation belongs to.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^IS[0-9a-fA-F]{32}$
	 */
	chat_service_sid?: string | null;
	/**
	 * The unique ID of the [Participant](https://www.twilio.com/docs/conversations/api/conversation-participant-resource).
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MB[0-9a-fA-F]{32}$
	 */
	participant_sid?: string | null;
	/**
	 * The unique string that identifies the conversation participant as [Conversation User](https://www.twilio.com/docs/conversations/api/user-resource).
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^US[0-9a-fA-F]{32}$
	 */
	participant_user_sid?: string | null;
	/**
	 * A unique string identifier for the conversation participant as [Conversation User](https://www.twilio.com/docs/conversations/api/user-resource). This parameter is non-null if (and only if) the participant is using the Conversations SDK to communicate. Limited to 256 characters.
	 * @nullable
	 */
	participant_identity?: string | null;
	/**
	 * Information about how this participant exchanges messages with the conversation. A JSON parameter consisting of type and address fields of the participant.
	 * @nullable
	 */
	participant_messaging_binding?: ConversationsV1ParticipantConversationParticipantMessagingBinding;
	/**
	 * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) this Participant belongs to.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^CH[0-9a-fA-F]{32}$
	 */
	conversation_sid?: string | null;
	/**
	 * An application-defined string that uniquely identifies the Conversation resource.
	 * @nullable
	 */
	conversation_unique_name?: string | null;
	/**
	 * The human-readable name of this conversation, limited to 256 characters. Optional.
	 * @nullable
	 */
	conversation_friendly_name?: string | null;
	/**
	 * An optional string metadata field you can use to store any data you wish. The string value must contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will be returned.
	 * @nullable
	 */
	conversation_attributes?: string | null;
	/**
	 * The date that this conversation was created, given in ISO 8601 format.
	 * @nullable
	 */
	conversation_date_created?: string | null;
	/**
	 * The date that this conversation was last updated, given in ISO 8601 format.
	 * @nullable
	 */
	conversation_date_updated?: string | null;
	/**
	 * Identity of the creator of this Conversation.
	 * @nullable
	 */
	conversation_created_by?: string | null;
	conversation_state?: ParticipantConversationEnumState;
	/**
	 * Timer date values representing state update for this conversation.
	 * @nullable
	 */
	conversation_timers?: ConversationsV1ParticipantConversationConversationTimers;
	/**
	 * Contains absolute URLs to access the [participant](https://www.twilio.com/docs/conversations/api/conversation-participant-resource) and [conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) of this conversation.
	 * @nullable
	 */
	links?: ConversationsV1ParticipantConversationLinks;
}
