/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface ConversationsV1ServiceServiceConfigurationServiceNotification {
	/**
	 * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this configuration.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The SID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) the Configuration applies to.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^IS[0-9a-fA-F]{32}$
	 */
	chat_service_sid?: string | null;
	/** The Push Notification configuration for New Messages. */
	new_message?: unknown | null;
	/** The Push Notification configuration for being added to a Conversation. */
	added_to_conversation?: unknown | null;
	/** The Push Notification configuration for being removed from a Conversation. */
	removed_from_conversation?: unknown | null;
	/**
	 * Weather the notification logging is enabled.
	 * @nullable
	 */
	log_enabled?: boolean | null;
	/**
	 * An absolute API resource URL for this configuration.
	 * @nullable
	 */
	url?: string | null;
}
