/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current state of this conversation. Can be either `initializing`, `active`, `inactive` or `closed` and defaults to `active`
 */
export type ConversationWithParticipantsEnumState =
	(typeof ConversationWithParticipantsEnumState)[keyof typeof ConversationWithParticipantsEnumState];

export const ConversationWithParticipantsEnumState = {
	initializing: "initializing",
	inactive: "inactive",
	active: "active",
	closed: "closed",
} as const;
