/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Timer date values representing state update for this conversation.
 * @nullable
 */
export type ConversationsV1ConversationWithParticipantsTimers = unknown | null;
