/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationsV1UserUserConversationLinks } from "./conversationsV1UserUserConversationLinks";
import type { UserConversationEnumNotificationLevel } from "./userConversationEnumNotificationLevel";
import type { UserConversationEnumState } from "./userConversationEnumState";

export interface ConversationsV1UserUserConversation {
	/**
	 * The unique ID of the [Account](https://www.twilio.com/docs/iam/api/account) responsible for this conversation.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The unique ID of the [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) this conversation belongs to.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^IS[0-9a-fA-F]{32}$
	 */
	chat_service_sid?: string | null;
	/**
	 * The unique ID of the [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) for this User Conversation.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^CH[0-9a-fA-F]{32}$
	 */
	conversation_sid?: string | null;
	/**
	 * The number of unread Messages in the Conversation for the Participant.
	 * @nullable
	 */
	unread_messages_count?: number | null;
	/**
	 * The index of the last Message in the Conversation that the Participant has read.
	 * @nullable
	 */
	last_read_message_index?: number | null;
	/**
	 * The unique ID of the [participant](https://www.twilio.com/docs/conversations/api/conversation-participant-resource) the user conversation belongs to.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MB[0-9a-fA-F]{32}$
	 */
	participant_sid?: string | null;
	/**
	 * The unique string that identifies the [User resource](https://www.twilio.com/docs/conversations/api/user-resource).
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^US[0-9a-fA-F]{32}$
	 */
	user_sid?: string | null;
	/**
	 * The human-readable name of this conversation, limited to 256 characters. Optional.
	 * @nullable
	 */
	friendly_name?: string | null;
	conversation_state?: UserConversationEnumState;
	/** Timer date values representing state update for this conversation. */
	timers?: unknown | null;
	/**
	 * An optional string metadata field you can use to store any data you wish. The string value must contain structurally valid JSON if specified.  **Note** that if the attributes are not set "{}" will be returned.
	 * @nullable
	 */
	attributes?: string | null;
	/**
	 * The date that this conversation was created, given in ISO 8601 format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date that this conversation was last updated, given in ISO 8601 format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * Identity of the creator of this Conversation.
	 * @nullable
	 */
	created_by?: string | null;
	notification_level?: UserConversationEnumNotificationLevel;
	/**
	 * An application-defined string that uniquely identifies the Conversation resource. It can be used to address the resource in place of the resource's `conversation_sid` in the URL.
	 * @nullable
	 */
	unique_name?: string | null;
	/** @nullable */
	url?: string | null;
	/**
	 * Contains absolute URLs to access the [participant](https://www.twilio.com/docs/conversations/api/conversation-participant-resource) and [conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) of this conversation.
	 * @nullable
	 */
	links?: ConversationsV1UserUserConversationLinks;
}
