/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current state of this conversation. Can be either `initializing`, `active`, `inactive` or `closed` and defaults to `active`
 */
export type ConversationEnumState = typeof ConversationEnumState[keyof typeof ConversationEnumState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationEnumState = {
  initializing: 'initializing',
  inactive: 'inactive',
  active: 'active',
  closed: 'closed',
} as const;
