/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The target of this webhook: `webhook`, `studio`, `trigger`
 */
export type ConversationScopedWebhookEnumTarget =
	(typeof ConversationScopedWebhookEnumTarget)[keyof typeof ConversationScopedWebhookEnumTarget];

export const ConversationScopedWebhookEnumTarget = {
	webhook: "webhook",
	trigger: "trigger",
	studio: "studio",
} as const;
