/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ConversationScopedWebhookEnumMethod = typeof ConversationScopedWebhookEnumMethod[keyof typeof ConversationScopedWebhookEnumMethod];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationScopedWebhookEnumMethod = {
  get: 'get',
  post: 'post',
} as const;
