/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ConversationMessageEnumOrderType =
	(typeof ConversationMessageEnumOrderType)[keyof typeof ConversationMessageEnumOrderType];

export const ConversationMessageEnumOrderType = {
	asc: "asc",
	desc: "desc",
} as const;
