/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateSubscribedEventBody = {
	/** Type of event being subscribed to. */
	Type: string;
	/** The schema version that the Subscription should use. */
	SchemaVersion?: number;
};
