/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateChannelSenderBody = {
	/**
	 * The SID of the Channel Sender being added to the Service.
	 * @minLength 34
	 * @maxLength 34
	 * @pattern ^XE[0-9a-fA-F]{32}$
	 */
	Sid: string;
};
