/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Accounts
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateCredentialAwsBody = {
	/** A string that contains the AWS access credentials in the format `<AWS_ACCESS_KEY_ID>:<AWS_SECRET_ACCESS_KEY>`. For example, `AKIAIOSFODNN7EXAMPLE:wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY` */
	Credentials: string;
	/** A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
	FriendlyName?: string;
	/**
	 * The SID of the Subaccount that this Credential should be associated with. Must be a valid Subaccount of the account issuing the request.
	 * @minLength 34
	 * @maxLength 34
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	AccountSid?: string;
};
