/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceConversationScopedWebhookEnumTarget } from './serviceConversationScopedWebhookEnumTarget';
import type { ServiceConversationScopedWebhookEnumMethod } from './serviceConversationScopedWebhookEnumMethod';

export type CreateServiceConversationScopedWebhookBody = {
  Target: ServiceConversationScopedWebhookEnumTarget;
  /** The absolute url the webhook request should be sent to. */
  'Configuration.Url'?: string;
  'Configuration.Method'?: ServiceConversationScopedWebhookEnumMethod;
  /** The list of events, firing webhook event for this Conversation. */
  'Configuration.Filters'?: string[];
  /** The list of keywords, firing webhook event for this Conversation. */
  'Configuration.Triggers'?: string[];
  /**
   * The studio flow SID, where the webhook should be sent to.
   * @minLength 34
   * @maxLength 34
   * @pattern ^FW[0-9a-fA-F]{32}$
   */
  'Configuration.FlowSid'?: string;
  /** The message index for which and it's successors the webhook will be replayed. Not set by default */
  'Configuration.ReplayAfter'?: number;
};
