/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The HTTP method we should use to call `fallback_url`. Can be: `GET` or `POST`.
 */
export type CreateServiceBodyFallbackMethod =
	(typeof CreateServiceBodyFallbackMethod)[keyof typeof CreateServiceBodyFallbackMethod];

export const CreateServiceBodyFallbackMethod = {
	GET: "GET",
	POST: "POST",
} as const;
