/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateAlphaSenderBody = {
	/** The Alphanumeric Sender ID string. Can be up to 11 characters long. Valid characters are A-Z, a-z, 0-9, space, hyphen `-`, plus `+`, underscore `_` and ampersand `&`. This value cannot contain only numbers. */
	AlphaSender: string;
};
