/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateShortCodeBody = {
	/**
	 * The SID of the ShortCode resource being added to the Service.
	 * @minLength 34
	 * @maxLength 34
	 * @pattern ^SC[0-9a-fA-F]{32}$
	 */
	ShortCodeSid: string;
};
