/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateSinkValidateBody = {
	/** A 34 character string that uniquely identifies the test event for a Sink being validated. */
	TestId: string;
};
