/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateBrandRegistrationsBody = {
	/**
	 * Customer Profile Bundle Sid.
	 * @minLength 34
	 * @maxLength 34
	 * @pattern ^BU[0-9a-fA-F]{32}$
	 */
	CustomerProfileBundleSid: string;
	/**
	 * A2P Messaging Profile Bundle Sid.
	 * @minLength 34
	 * @maxLength 34
	 * @pattern ^BU[0-9a-fA-F]{32}$
	 */
	A2PProfileBundleSid: string;
	/** Type of brand being created. One of: "STANDARD", "SOLE_PROPRIETOR". SOLE_PROPRIETOR is for low volume, SOLE_PROPRIETOR use cases. STANDARD is for all other use cases. */
	BrandType?: string;
	/** A boolean that specifies whether brand should be a mock or not. If true, brand will be registered as a mock brand. Defaults to false if no value is provided. */
	Mock?: boolean;
	/** A flag to disable automatic secondary vetting for brands which it would otherwise be done. */
	SkipAutomaticSecVet?: boolean;
};
