/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The HTTP method we should use to call `inbound_request_url`. Can be `GET` or `POST` and the default is `POST`.
 */
export type CreateServiceBodyInboundMethod =
	(typeof CreateServiceBodyInboundMethod)[keyof typeof CreateServiceBodyInboundMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateServiceBodyInboundMethod = {
	GET: "GET",
	POST: "POST",
} as const;
