/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type CreateServiceBody = {
  /** The human-readable name of this service, limited to 256 characters. Optional. */
  FriendlyName: string;
};
