/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of push-notification service the credential is for. Can be: `fcm`, `gcm`, or `apn`.
 */
export type CredentialEnumPushType =
	(typeof CredentialEnumPushType)[keyof typeof CredentialEnumPushType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CredentialEnumPushType = {
	apn: "apn",
	gcm: "gcm",
	fcm: "fcm",
} as const;
