/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Contains a dictionary of URL links to nested resources of this schema.
 * @nullable
 */
export type EventsV1SchemaLinks = { [key: string]: unknown } | null;
