/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1SinkLinks } from "./eventsV1SinkLinks";
import type { SinkEnumSinkType } from "./sinkEnumSinkType";
import type { SinkEnumStatus } from "./sinkEnumStatus";

export interface EventsV1Sink {
	/**
	 * The date that this Sink was created, given in ISO 8601 format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date that this Sink was updated, given in ISO 8601 format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * A human readable description for the Sink
	 * @nullable
	 */
	description?: string | null;
	/**
	 * A 34 character string that uniquely identifies this Sink.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^DG[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/** The information required for Twilio to connect to the provided Sink encoded as JSON. */
	sink_configuration?: unknown | null;
	sink_type?: SinkEnumSinkType;
	status?: SinkEnumStatus;
	/**
	 * The URL of this resource.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * Contains a dictionary of URL links to nested resources of this Sink.
	 * @nullable
	 */
	links?: EventsV1SinkLinks;
}
