/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1EventTypeLinks } from "./eventsV1EventTypeLinks";

export interface EventsV1EventType {
	/**
	 * A string that uniquely identifies this Event Type.
	 * @nullable
	 */
	type?: string | null;
	/**
	 * A string that uniquely identifies the Schema this Event Type adheres to.
	 * @nullable
	 */
	schema_id?: string | null;
	/**
	 * The date that this Event Type was created, given in ISO 8601 format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date that this Event Type was updated, given in ISO 8601 format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * A human readable description for this Event Type.
	 * @nullable
	 */
	description?: string | null;
	/**
	 * A string that describes how this Event Type can be used. For example: `available`, `deprecated`, `restricted`, `discontinued`. When the status is `available`, the Event Type can be used normally.
	 * @nullable
	 */
	status?: string | null;
	/**
	 * The URL to the documentation or to the most relevant Twilio Changelog entry of this Event Type.
	 * @nullable
	 */
	documentation_url?: string | null;
	/**
	 * The URL of this resource.
	 * @nullable
	 */
	url?: string | null;
	/** @nullable */
	links?: EventsV1EventTypeLinks;
}
