/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The information required for Twilio to connect to the provided Sink encoded as JSON.
 * @nullable
 */
export type EventsV1SinkSinkConfiguration = unknown | null;
