/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface EventsV1SinkSinkTest {
  /**
   * Feedback indicating whether the test event was generated.
   * @nullable
   */
  result?: string | null;
}
