/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1SchemaLinks } from "./eventsV1SchemaLinks";

export interface EventsV1Schema {
	/**
	 * The unique identifier of the schema. Each schema can have multiple versions, that share the same id.
	 * @nullable
	 */
	id?: string | null;
	/**
	 * The URL of this resource.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * Contains a dictionary of URL links to nested resources of this schema.
	 * @nullable
	 */
	links?: EventsV1SchemaLinks;
	/**
	 * The date that the latest schema version was created, given in ISO 8601 format.
	 * @nullable
	 */
	latest_version_date_created?: string | null;
	/** The latest version published of this schema. */
	latest_version?: number;
}
