/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1SubscriptionLinks } from "./eventsV1SubscriptionLinks";

export interface EventsV1Subscription {
	/**
	 * The unique SID identifier of the Account.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * A 34 character string that uniquely identifies this Subscription.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^DF[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The date that this Subscription was created, given in ISO 8601 format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date that this Subscription was updated, given in ISO 8601 format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * A human readable description for the Subscription
	 * @nullable
	 */
	description?: string | null;
	/**
	 * The SID of the sink that events selected by this subscription should be sent to. Sink must be active for the subscription to be created.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^DG[0-9a-fA-F]{32}$
	 */
	sink_sid?: string | null;
	/**
	 * The URL of this resource.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * Contains a dictionary of URL links to nested resources of this Subscription.
	 * @nullable
	 */
	links?: EventsV1SubscriptionLinks;
}
