/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Accounts
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type FetchMessagingGeopermissionsParams = {
	/**
	 * The country code to filter the geo permissions. If provided, only the geo permission for the specified country will be returned.
	 */
	CountryCode?: string;
};
