/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type FetchDeactivationParams = {
	/**
	 * The request will return a list of all United States Phone Numbers that were deactivated on the day specified by this parameter. This date should be specified in YYYY-MM-DD format.
	 */
	Date?: string;
};
