/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KeywordTypeConfig } from './keywordTypeConfig';

/**
 * Response containing keyword configurations organized by keyword type
 */
export interface KeywordConfigurationResponse {[key: string]: KeywordTypeConfig}
