/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KeywordItem } from "./keywordItem";

/**
 * Configuration for a specific keyword type (STOP, START, HELP, etc.)
 */
export interface KeywordTypeConfig {
	/**
	 * List of keywords associated with this keyword type
	 * @minItems 1
	 */
	keywords: KeywordItem[];
	/**
	 * The response message sent when any keyword of this type is received
	 * @minLength 1
	 * @maxLength 1600
	 */
	message: string;
}
