/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The language key/identifier (typically uppercase)
 */
export type LanguagePropertiesKey =
	(typeof LanguagePropertiesKey)[keyof typeof LanguagePropertiesKey];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LanguagePropertiesKey = {
	ALL: "ALL",
	AFRIKAANS: "AFRIKAANS",
	ARABIC: "ARABIC",
	BENGALI: "BENGALI",
	CHINESE: "CHINESE",
	CROATIAN: "CROATIAN",
	CZECH: "CZECH",
	DANISH: "DANISH",
	DUTCH: "DUTCH",
	ENGLISH: "ENGLISH",
	ESTONIAN: "ESTONIAN",
	FINNISH: "FINNISH",
	FRENCH: "FRENCH",
	GERMAN: "GERMAN",
	GREEK: "GREEK",
	HEBREW: "HEBREW",
	HINDI: "HINDI",
	HUNGARIAN: "HUNGARIAN",
	ITALIAN: "ITALIAN",
	JAPANESE: "JAPANESE",
	KOREAN: "KOREAN",
	LATVIAN: "LATVIAN",
	LITHUANIAN: "LITHUANIAN",
	MALAY: "MALAY",
	MALAYSIAN: "MALAYSIAN",
	NORWEGIAN: "NORWEGIAN",
	POLISH: "POLISH",
	PORTUGUESE: "PORTUGUESE",
	RUSSIAN: "RUSSIAN",
	SLOVAK: "SLOVAK",
	SLOVENE: "SLOVENE",
	SPANISH: "SPANISH",
	SOUTHERN_NDEBELE: "SOUTHERN_NDEBELE",
	SOUTHERN_SOTHO: "SOUTHERN_SOTHO",
	SWATI: "SWATI",
	SWEDISH: "SWEDISH",
	TAMIL: "TAMIL",
	TSWANA: "TSWANA",
	TSONGA: "TSONGA",
	VENDA: "VENDA",
	XHOSA: "XHOSA",
	ZULU: "ZULU",
} as const;
