/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { BrandVettingEnumVettingProvider } from "./brandVettingEnumVettingProvider";

export type ListBrandVettingParams = {
	/**
	 * The third-party provider of the vettings to read
	 */
	VettingProvider?: BrandVettingEnumVettingProvider;
};
