/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ListTollfreeVerification200Meta } from "./listTollfreeVerification200Meta";
import type { MessagingV1TollfreeVerification } from "./messagingV1TollfreeVerification";

export type ListTollfreeVerification200 = {
	verifications?: MessagingV1TollfreeVerification[];
	meta?: ListTollfreeVerification200Meta;
};
