/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ServiceBindingEnumBindingType } from "./serviceBindingEnumBindingType";

export type ListServiceBindingParams = {
	/**
	 * The push technology used by the Binding resources to read.  Can be: `apn`, `gcm`, `fcm`, or `twilsock`.  See [push notification configuration](https://www.twilio.com/docs/chat/push-notification-configuration) for more info.
	 */
	BindingType?: ServiceBindingEnumBindingType[];
	/**
	 * The identity of a [Conversation User](https://www.twilio.com/docs/conversations/api/user-resource) this binding belongs to. See [access tokens](https://www.twilio.com/docs/conversations/create-tokens) for more details.
	 */
	Identity?: string[];
	/**
	 * How many resources to return in each list page. The default is 50, and the maximum is 100.
	 * @minimum 1
	 * @maximum 100
	 */
	PageSize?: number;
	/**
	 * The page index. This value is simply for client state.
	 * @minimum 0
	 */
	Page?: number;
	/**
	 * The page token. This is provided by the API.
	 */
	PageToken?: string;
};
