import type { ListBrandRegistrations200Meta } from "./listBrandRegistrations200Meta";
/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1BrandRegistrations } from "./messagingV1BrandRegistrations";

export type ListBrandRegistrations200 = {
	data?: MessagingV1BrandRegistrations[];
	meta?: ListBrandRegistrations200Meta;
};
