import type { ListShortCode200Meta } from "./listShortCode200Meta";
/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1ServiceShortCode } from "./messagingV1ServiceShortCode";

export type ListShortCode200 = {
	short_codes?: MessagingV1ServiceShortCode[];
	meta?: ListShortCode200Meta;
};
