/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationsV1ServiceServiceUserServiceUserConversation } from "./conversationsV1ServiceServiceUserServiceUserConversation";
import type { ListServiceUserConversation200Meta } from "./listServiceUserConversation200Meta";

export type ListServiceUserConversation200 = {
	conversations?: ConversationsV1ServiceServiceUserServiceUserConversation[];
	meta?: ListServiceUserConversation200Meta;
};
