/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Accounts
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ListCredentialPublicKey200Meta = {
	first_page_url?: string;
	key?: string;
	/** @nullable */
	next_page_url?: string | null;
	page?: number;
	page_size?: number;
	/** @nullable */
	previous_page_url?: string | null;
	url?: string;
};
