/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ListPhoneNumber200Meta } from "./listPhoneNumber200Meta";
import type { MessagingV1ServicePhoneNumber } from "./messagingV1ServicePhoneNumber";

export type ListPhoneNumber200 = {
	phone_numbers?: MessagingV1ServicePhoneNumber[];
	meta?: ListPhoneNumber200Meta;
};
