/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ListUserParams = {
	/**
	 * How many resources to return in each list page. The default is 50, and the maximum is 50.
	 * @minimum 1
	 * @maximum 50
	 */
	PageSize?: number;
	/**
	 * The page index. This value is simply for client state.
	 * @minimum 0
	 */
	Page?: number;
	/**
	 * The page token. This is provided by the API.
	 */
	PageToken?: string;
};
