import type { ListUsAppToPerson200Meta } from "./listUsAppToPerson200Meta";
/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1ServiceUsAppToPerson } from "./messagingV1ServiceUsAppToPerson";

export type ListUsAppToPerson200 = {
	compliance?: MessagingV1ServiceUsAppToPerson[];
	meta?: ListUsAppToPerson200Meta;
};
