import type { ListService200Meta } from "./listService200Meta";
/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1Service } from "./messagingV1Service";

export type ListService200 = {
	services?: MessagingV1Service[];
	meta?: ListService200Meta;
};
