/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationsV1Service } from './conversationsV1Service';
import type { ListService200Meta } from './listService200Meta';

export type ListService200 = {
  services?: ConversationsV1Service[];
  meta?: ListService200Meta;
};
