/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1SchemaSchemaVersion } from "./eventsV1SchemaSchemaVersion";
import type { ListSchemaVersion200Meta } from "./listSchemaVersion200Meta";

export type ListSchemaVersion200 = {
	schema_versions?: EventsV1SchemaSchemaVersion[];
	meta?: ListSchemaVersion200Meta;
};
