/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1Subscription } from './eventsV1Subscription';
import type { ListSubscription200Meta } from './listSubscription200Meta';

export type ListSubscription200 = {
  subscriptions?: EventsV1Subscription[];
  meta?: ListSubscription200Meta;
};
