/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1Sink } from "./eventsV1Sink";
import type { ListSink200Meta } from "./listSink200Meta";

export type ListSink200 = {
	sinks?: EventsV1Sink[];
	meta?: ListSink200Meta;
};
