/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1ServiceChannelSender } from './messagingV1ServiceChannelSender';
import type { ListChannelSender200Meta } from './listChannelSender200Meta';

export type ListChannelSender200 = {
  senders?: MessagingV1ServiceChannelSender[];
  meta?: ListChannelSender200Meta;
};
