/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ListDestinationAlphaSender200Meta } from "./listDestinationAlphaSender200Meta";
import type { MessagingV1ServiceDestinationAlphaSender } from "./messagingV1ServiceDestinationAlphaSender";

export type ListDestinationAlphaSender200 = {
	alpha_senders?: MessagingV1ServiceDestinationAlphaSender[];
	meta?: ListDestinationAlphaSender200Meta;
};
