/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ListSubscribedEvent200Meta = {
  first_page_url?: string;
  key?: string;
  /** @nullable */
  next_page_url?: string | null;
  page?: number;
  page_size?: number;
  /** @nullable */
  previous_page_url?: string | null;
  url?: string;
};
