/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConversationsV1ServiceServiceConversationServiceConversationMessageServiceConversationMessageReceipt } from "./conversationsV1ServiceServiceConversationServiceConversationMessageServiceConversationMessageReceipt";
import type { ListServiceConversationMessageReceipt200Meta } from "./listServiceConversationMessageReceipt200Meta";

export type ListServiceConversationMessageReceipt200 = {
	delivery_receipts?: ConversationsV1ServiceServiceConversationServiceConversationMessageServiceConversationMessageReceipt[];
	meta?: ListServiceConversationMessageReceipt200Meta;
};
