/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ListUsAppToPerson200Meta } from "./listUsAppToPerson200Meta";
import type { MessagingV1ServiceUsAppToPersonResponse } from "./messagingV1ServiceUsAppToPersonResponse";

export type ListUsAppToPerson200 = {
	compliance?: MessagingV1ServiceUsAppToPersonResponse[];
	meta?: ListUsAppToPerson200Meta;
};
