/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ListBrandVetting200Meta } from "./listBrandVetting200Meta";
import type { MessagingV1BrandRegistrationsBrandVetting } from "./messagingV1BrandRegistrationsBrandVetting";

export type ListBrandVetting200 = {
	data?: MessagingV1BrandRegistrationsBrandVetting[];
	meta?: ListBrandVetting200Meta;
};
