/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ListServiceParticipantConversationParams = {
/**
 * A unique string identifier for the conversation participant as [Conversation User](https://www.twilio.com/docs/conversations/api/user-resource). This parameter is non-null if (and only if) the participant is using the Conversations SDK to communicate. Limited to 256 characters.
 */
Identity?: string;
/**
 * A unique string identifier for the conversation participant who's not a Conversation User. This parameter could be found in messaging_binding.address field of Participant resource. It should be url-encoded.
 */
Address?: string;
/**
 * How many resources to return in each list page. The default is 50, and the maximum is 50.
 * @minimum 1
 * @maximum 50
 */
PageSize?: number;
/**
 * The page index. This value is simply for client state.
 * @minimum 0
 */
Page?: number;
/**
 * The page token. This is provided by the API.
 */
PageToken?: string;
};
