/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { EventsV1SubscriptionSubscribedEvent } from "./eventsV1SubscriptionSubscribedEvent";
import type { ListSubscribedEvent200Meta } from "./listSubscribedEvent200Meta";

export type ListSubscribedEvent200 = {
	types?: EventsV1SubscriptionSubscribedEvent[];
	meta?: ListSubscribedEvent200Meta;
};
