/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { LanguageProperties } from './languageProperties';

export interface LocaleResponse {
  /** List of supported languages for opt-out configurations */
  languages: LanguageProperties[];
}
