/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessageProperties {
	/** The keyword type in format KeywordType.Locale (e.g., STOP.ENGLISH, HELP.FRENCH) */
	keyword_type: string;
	/** The message type identifier (typically country codes or special identifiers) */
	message_type: string;
	/** The actual opt-out message text to be sent */
	message: string;
}
