/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1ServiceChannelSender {
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ChannelSender resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The SID of the [Service](https://www.twilio.com/docs/messaging/services) the resource is associated with.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MG[0-9a-fA-F]{32}$
	 */
	messaging_service_sid?: string | null;
	/**
	 * The unique string that we created to identify the ChannelSender resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^XE[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The unique string that identifies the sender e.g whatsapp:+123456XXXX.
	 * @nullable
	 */
	sender?: string | null;
	/**
	 * A string value that identifies the sender type e.g WhatsApp, Messenger.
	 * @nullable
	 */
	sender_type?: string | null;
	/**
	 * The 2-character [ISO Country Code](https://www.iso.org/iso-3166-country-codes.html) of the number.
	 * @nullable
	 */
	country_code?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * The absolute URL of the ChannelSender resource.
	 * @nullable
	 */
	url?: string | null;
}
