/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1RequestManagedCert {
	/**
	 * The unique string that we created to identify the Domain resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^DN[0-9a-fA-F]{32}$
	 */
	domain_sid?: string | null;
	/**
	 * Date that this Domain was last updated.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * Date that this Domain was registered to the Twilio platform to create a new Domain object.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * Date that the private certificate associated with this domain expires. This is the expiration date of your existing cert.
	 * @nullable
	 */
	date_expires?: string | null;
	/**
	 * Full url path for this domain.
	 * @nullable
	 */
	domain_name?: string | null;
	/**
	 * The unique string that we created to identify this Certificate resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^CW[0-9a-fA-F]{32}$
	 */
	certificate_sid?: string | null;
	/** @nullable */
	url?: string | null;
	/**
	 * A boolean flag indicating if the certificate is managed by Twilio.
	 * @nullable
	 */
	managed?: boolean | null;
	/**
	 * A boolean flag indicating if a managed certificate needs to be fulfilled by Twilio.
	 * @nullable
	 */
	requesting?: boolean | null;
}
