/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1Deactivation {
  /**
   * Returns an authenticated url that redirects to a file containing the deactivated numbers for the requested day. This url is valid for up to two minutes.
   * @nullable
   */
  redirect_to?: string | null;
}
