/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1ServiceUsAppToPerson } from "./messagingV1ServiceUsAppToPerson";
import type { MessagingV1ServiceUsAppToPersonV2 } from "./messagingV1ServiceUsAppToPersonV2";

export type MessagingV1ServiceUsAppToPersonResponse =
	| MessagingV1ServiceUsAppToPerson
	| MessagingV1ServiceUsAppToPersonV2;
