/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1Usecase {
	/**
	 * Human readable use case details (usecase, description and purpose) of Messaging Service Use Cases.
	 * @nullable
	 */
	usecases?: unknown[] | null;
}
