/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1ServiceDestinationAlphaSender {
	/**
	 * The unique string that we created to identify the AlphaSender resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AI[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the AlphaSender resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MG[0-9a-fA-F]{32}$
	 */
	service_sid?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * The Alphanumeric Sender ID string.
	 * @nullable
	 */
	alpha_sender?: string | null;
	/**
	 * An array of values that describe whether the number can receive calls or messages. Can be: `SMS`.
	 * @nullable
	 */
	capabilities?: string[] | null;
	/**
	 * The absolute URL of the AlphaSender resource.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * The Two Character ISO Country Code the Alphanumeric Sender ID will be used for. For Default Alpha Senders that work across countries, this value will be an empty string
	 * @nullable
	 */
	iso_country_code?: string | null;
}
