/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Rate limit and/or classification set by each carrier, Ex. AT&T or T-Mobile.
 * @nullable
 */
export type MessagingV1ServiceUsAppToPersonRateLimits = unknown | null;
