/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1ServiceAddons {
	/** The unique string that we created to identify the add on resource. */
	sid?: string;
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the add on resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MG[0-9a-fA-F]{32}$
	 */
	service_sid?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * The SID that identifies the add on type.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AO[0-9a-fA-F]{32}$
	 */
	add_on_type_sid?: string | null;
	/**
	 * The config of the add on in JSON string format.
	 * @nullable
	 */
	add_on_config?: string | null;
	/**
	 * The absolute URL of the add on resource.
	 * @nullable
	 */
	url?: string | null;
}
