/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The HTTP method we use to call `fallback_url`. Can be: `GET` or `POST`.
 * @nullable
 */
export type MessagingV1ServiceFallbackMethod =
	| (typeof MessagingV1ServiceFallbackMethod)[keyof typeof MessagingV1ServiceFallbackMethod]
	| null;

export const MessagingV1ServiceFallbackMethod = {
	GET: "GET",
	POST: "POST",
} as const;
