/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1ServiceUsAppToPersonUsecase {
	/**
	 * Human readable name, code, description and post_approval_required (indicates whether or not post approval is required for this Use Case) of A2P Campaign Use Cases.
	 * @nullable
	 */
	us_app_to_person_usecases?: unknown[] | null;
}
