/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { BrandRegistrationsEnumStatus } from "./brandRegistrationsEnumStatus";
import type { BrandRegistrationsEnumBrandFeedback } from "./brandRegistrationsEnumBrandFeedback";
import type { BrandRegistrationsEnumIdentityStatus } from "./brandRegistrationsEnumIdentityStatus";
import type { MessagingV1BrandRegistrationsLinks } from "./messagingV1BrandRegistrationsLinks";

export interface MessagingV1BrandRegistrations {
	/**
	 * The unique string to identify Brand Registration.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^BN[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Brand Registration resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * A2P Messaging Profile Bundle BundleSid.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^BU[0-9a-fA-F]{32}$
	 */
	customer_profile_bundle_sid?: string | null;
	/**
	 * A2P Messaging Profile Bundle BundleSid.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^BU[0-9a-fA-F]{32}$
	 */
	a2p_profile_bundle_sid?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * Type of brand. One of: "STANDARD", "SOLE_PROPRIETOR". SOLE_PROPRIETOR is for the low volume, SOLE_PROPRIETOR campaign use case. There can only be one SOLE_PROPRIETOR campaign created per SOLE_PROPRIETOR brand. STANDARD is for all other campaign use cases. Multiple campaign use cases can be created per STANDARD brand.
	 * @nullable
	 */
	brand_type?: string | null;
	status?: BrandRegistrationsEnumStatus;
	/**
	 * Campaign Registry (TCR) Brand ID. Assigned only after successful brand registration.
	 * @nullable
	 */
	tcr_id?: string | null;
	/**
	 * DEPRECATED. A reason why brand registration has failed. Only applicable when status is FAILED.
	 * @nullable
	 */
	failure_reason?: string | null;
	/**
	 * A list of errors that occurred during the brand registration process.
	 * @nullable
	 */
	errors?: unknown[] | null;
	/**
	 * The absolute URL of the Brand Registration resource.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * The secondary vetting score if it was done. Otherwise, it will be the brand score if it's returned from TCR. It may be null if no score is available.
	 * @nullable
	 */
	brand_score?: number | null;
	/**
	 * DEPRECATED. Feedback on how to improve brand score
	 * @nullable
	 */
	brand_feedback?: BrandRegistrationsEnumBrandFeedback[] | null;
	identity_status?: BrandRegistrationsEnumIdentityStatus;
	/**
	 * Publicly traded company identified in the Russell 3000 Index
	 * @nullable
	 */
	russell_3000?: boolean | null;
	/**
	 * Identified as a government entity
	 * @nullable
	 */
	government_entity?: boolean | null;
	/**
	 * Nonprofit organization tax-exempt status per section 501 of the U.S. tax code.
	 * @nullable
	 */
	tax_exempt_status?: string | null;
	/**
	 * A flag to disable automatic secondary vetting for brands which it would otherwise be done.
	 * @nullable
	 */
	skip_automatic_sec_vet?: boolean | null;
	/**
	 * A boolean that specifies whether brand should be a mock or not. If true, brand will be registered as a mock brand. Defaults to false if no value is provided.
	 * @nullable
	 */
	mock?: boolean | null;
	/** @nullable */
	links?: MessagingV1BrandRegistrationsLinks;
}
