/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of business, valid values are PRIVATE_PROFIT, PUBLIC_PROFIT, NON_PROFIT, SOLE_PROPRIETOR, GOVERNMENT
 * @nullable
 */
export type MessagingV1TollfreeVerificationBusinessType =
	| (typeof MessagingV1TollfreeVerificationBusinessType)[keyof typeof MessagingV1TollfreeVerificationBusinessType]
	| null;

export const MessagingV1TollfreeVerificationBusinessType = {
	PRIVATE_PROFIT: "PRIVATE_PROFIT",
	PUBLIC_PROFIT: "PUBLIC_PROFIT",
	SOLE_PROPRIETOR: "SOLE_PROPRIETOR",
	NON_PROFIT: "NON_PROFIT",
	GOVERNMENT: "GOVERNMENT",
} as const;
