/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1LinkshorteningMessagingService {
  /**
   * The unique string identifies the domain resource
   * @minLength 34
   * @maxLength 34
   * @nullable
   * @pattern ^DN[0-9a-fA-F]{32}$
   */
  domain_sid?: string | null;
  /**
   * The unique string that identifies the messaging service
   * @minLength 34
   * @maxLength 34
   * @nullable
   * @pattern ^MG[0-9a-fA-F]{32}$
   */
  messaging_service_sid?: string | null;
  /** @nullable */
  url?: string | null;
}
