/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessageTypeConfig {
  /** The message type key/identifier (typically country codes or special identifiers) */
  key: string;
  /** Human-readable display name for the message type */
  friendly_name: string;
}
