/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessageProperties } from "./messageProperties";

export interface MessagesResponse {
	/**
	 * The SID of the account that owns this opt-out configuration
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid: string;
	/**
	 * The SID of the opt-out configuration
	 * @pattern ^OO[0-9a-fA-F]{32}$
	 */
	opt_out_sid: string;
	/** List of message configurations for different keyword types */
	config: MessageProperties[];
}
