/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1ExternalCampaign {
	/**
	 * The unique string that identifies a US A2P Compliance resource `QE2c6890da8086d771620e9b13fadeba0b`.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^QE[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that the Campaign belongs to.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * ID of the preregistered campaign.
	 * @nullable
	 */
	campaign_id?: string | null;
	/**
	 * The SID of the [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) that the resource is associated with.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MG[0-9a-fA-F]{32}$
	 */
	messaging_service_sid?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
}
