/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Optional JSON field describing the status and upload date of a new certificate in the process of validation
 * @nullable
 */
export type MessagingV1DomainCertV4CertInValidation = unknown | null;
