/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1ServiceInboundMethod } from "./messagingV1ServiceInboundMethod";
import type { MessagingV1ServiceFallbackMethod } from "./messagingV1ServiceFallbackMethod";
import type { ServiceEnumScanMessageContent } from "./serviceEnumScanMessageContent";
import type { MessagingV1ServiceLinks } from "./messagingV1ServiceLinks";

export interface MessagingV1Service {
	/**
	 * The unique string that we created to identify the Service resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MG[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Service resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The string that you assigned to describe the resource.
	 * @nullable
	 */
	friendly_name?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * The URL we call using `inbound_method` when a message is received by any phone number or short code in the Service. When this property is `null`, receiving inbound messages is disabled. All messages sent to the Twilio phone number or short code will not be logged and received on the Account. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `inbound_request_url` defined for the Messaging Service.
	 * @nullable
	 */
	inbound_request_url?: string | null;
	/**
	 * The HTTP method we use to call `inbound_request_url`. Can be `GET` or `POST`.
	 * @nullable
	 */
	inbound_method?: MessagingV1ServiceInboundMethod;
	/**
	 * The URL that we call using `fallback_method` if an error occurs while retrieving or executing the TwiML from the Inbound Request URL. If the `use_inbound_webhook_on_number` field is enabled then the webhook url defined on the phone number will override the `fallback_url` defined for the Messaging Service.
	 * @nullable
	 */
	fallback_url?: string | null;
	/**
	 * The HTTP method we use to call `fallback_url`. Can be: `GET` or `POST`.
	 * @nullable
	 */
	fallback_method?: MessagingV1ServiceFallbackMethod;
	/**
	 * The URL we call to [pass status updates](https://www.twilio.com/docs/sms/api/message-resource#message-status-values) about message delivery.
	 * @nullable
	 */
	status_callback?: string | null;
	/**
	 * Whether to enable [Sticky Sender](https://www.twilio.com/docs/messaging/services#sticky-sender) on the Service instance.
	 * @nullable
	 */
	sticky_sender?: boolean | null;
	/**
	 * Whether to enable the [MMS Converter](https://www.twilio.com/docs/messaging/services#mms-converter) for messages sent through the Service instance.
	 * @nullable
	 */
	mms_converter?: boolean | null;
	/**
	 * Whether to enable [Smart Encoding](https://www.twilio.com/docs/messaging/services#smart-encoding) for messages sent through the Service instance.
	 * @nullable
	 */
	smart_encoding?: boolean | null;
	scan_message_content?: ServiceEnumScanMessageContent;
	/**
	 * [OBSOLETE] Former feature used to fallback to long code sender after certain short code message failures.
	 * @nullable
	 */
	fallback_to_long_code?: boolean | null;
	/**
	 * Whether to enable [Area Code Geomatch](https://www.twilio.com/docs/messaging/services#area-code-geomatch) on the Service Instance.
	 * @nullable
	 */
	area_code_geomatch?: boolean | null;
	/**
	 * Reserved.
	 * @nullable
	 */
	synchronous_validation?: boolean | null;
	/** How long, in seconds, messages sent from the Service are valid. Can be an integer from `1` to `36,000`. Default value is `36,000`. */
	validity_period?: number;
	/**
	 * The absolute URL of the Service resource.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * The absolute URLs of related resources.
	 * @nullable
	 */
	links?: MessagingV1ServiceLinks;
	/**
	 * A string that describes the scenario in which the Messaging Service will be used. Possible values are `notifications`, `marketing`, `verification`, `discussion`, `poll`, `undeclared`.
	 * @nullable
	 */
	usecase?: string | null;
	/**
	 * Whether US A2P campaign is registered for this Service.
	 * @nullable
	 */
	us_app_to_person_registered?: boolean | null;
	/**
	 * A boolean value that indicates either the webhook url configured on the phone number will be used or `inbound_request_url`/`fallback_url` url will be called when a message is received from the phone number. If this field is enabled then the webhook url defined on the phone number will override the `inbound_request_url`/`fallback_url` defined for the Messaging Service.
	 * @nullable
	 */
	use_inbound_webhook_on_number?: boolean | null;
}
