/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * @nullable
 */
export type MessagingV1BrandRegistrationsLinks = {
	[key: string]: unknown;
} | null;
