/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessagingV1TollfreeVerificationBusinessType } from "./messagingV1TollfreeVerificationBusinessType";
import type { TollfreeVerificationEnumOptInType } from "./tollfreeVerificationEnumOptInType";
import type { TollfreeVerificationEnumStatus } from "./tollfreeVerificationEnumStatus";
import type { TollfreeVerificationEnumVettingProvider } from "./tollfreeVerificationEnumVettingProvider";

export interface MessagingV1TollfreeVerification {
	/**
	 * The unique string to identify Tollfree Verification.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^HH[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the Tollfree Verification resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * Customer's Profile Bundle BundleSid.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^BU[0-9a-fA-F]{32}$
	 */
	customer_profile_sid?: string | null;
	/**
	 * Tollfree TrustProduct Bundle BundleSid.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^BU[0-9a-fA-F]{32}$
	 */
	trust_product_sid?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * The SID of the Regulated Item.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^RA[0-9a-fA-F]{32}$
	 */
	regulated_item_sid?: string | null;
	/**
	 * The name of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_name?: string | null;
	/**
	 * The address of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_street_address?: string | null;
	/**
	 * The address of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_street_address2?: string | null;
	/**
	 * The city of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_city?: string | null;
	/**
	 * The state/province/region of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_state_province_region?: string | null;
	/**
	 * The postal code of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_postal_code?: string | null;
	/**
	 * The country of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_country?: string | null;
	/**
	 * The website of the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_website?: string | null;
	/**
	 * The first name of the contact for the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_contact_first_name?: string | null;
	/**
	 * The last name of the contact for the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_contact_last_name?: string | null;
	/**
	 * The email address of the contact for the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_contact_email?: string | null;
	/**
	 * The E.164 formatted phone number of the contact for the business or organization using the Tollfree number.
	 * @nullable
	 */
	business_contact_phone?: string | null;
	/**
	 * The email address to receive the notification about the verification result. .
	 * @nullable
	 */
	notification_email?: string | null;
	/**
	 * The category of the use case for the Tollfree Number. List as many are applicable..
	 * @nullable
	 */
	use_case_categories?: string[] | null;
	/**
	 * Use this to further explain how messaging is used by the business or organization.
	 * @nullable
	 */
	use_case_summary?: string | null;
	/**
	 * An example of message content, i.e. a sample message.
	 * @nullable
	 */
	production_message_sample?: string | null;
	/**
	 * Link to an image that shows the opt-in workflow. Multiple images allowed and must be a publicly hosted URL.
	 * @nullable
	 */
	opt_in_image_urls?: string[] | null;
	opt_in_type?: TollfreeVerificationEnumOptInType;
	/**
	 * Estimate monthly volume of messages from the Tollfree Number.
	 * @nullable
	 */
	message_volume?: string | null;
	/**
	 * Additional information to be provided for verification.
	 * @nullable
	 */
	additional_information?: string | null;
	/**
	 * The SID of the Phone Number associated with the Tollfree Verification.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^PN[0-9a-fA-F]{32}$
	 */
	tollfree_phone_number_sid?: string | null;
	/**
	 * The E.164 formatted toll-free phone number associated with the verification.
	 * @nullable
	 */
	tollfree_phone_number?: string | null;
	status?: TollfreeVerificationEnumStatus;
	/**
	 * The absolute URL of the Tollfree Verification resource.
	 * @nullable
	 */
	url?: string | null;
	/**
	 * The rejection reason given when a Tollfree Verification has been rejected.
	 * @nullable
	 */
	rejection_reason?: string | null;
	/**
	 * The error code given when a Tollfree Verification has been rejected.
	 * @nullable
	 */
	error_code?: number | null;
	/**
	 * The date and time when the ability to edit a rejected verification expires.
	 * @nullable
	 */
	edit_expiration?: string | null;
	/**
	 * If a rejected verification is allowed to be edited/resubmitted. Some rejection reasons allow editing and some do not.
	 * @nullable
	 */
	edit_allowed?: boolean | null;
	/**
	 * A legally recognized business registration number
	 * @nullable
	 */
	business_registration_number?: string | null;
	/**
	 * The organizational authority for business registrations
	 * @nullable
	 */
	business_registration_authority?: string | null;
	/**
	 * Country business is registered in
	 * @nullable
	 */
	business_registration_country?: string | null;
	/**
	 * The type of business, valid values are PRIVATE_PROFIT, PUBLIC_PROFIT, NON_PROFIT, SOLE_PROPRIETOR, GOVERNMENT
	 * @nullable
	 */
	business_type?: MessagingV1TollfreeVerificationBusinessType;
	/**
	 * The E.164 formatted number associated with the business.
	 * @nullable
	 */
	business_registration_phone_number?: string | null;
	/**
	 * Trade name, sub entity, or downstream business name of business being submitted for verification
	 * @nullable
	 */
	doing_business_as?: string | null;
	/**
	 * The confirmation message sent to users when they opt in to receive messages.
	 * @nullable
	 */
	opt_in_confirmation_message?: string | null;
	/**
	 * A sample help message provided to users.
	 * @nullable
	 */
	help_message_sample?: string | null;
	/**
	 * The URL to the privacy policy for the business or organization.
	 * @nullable
	 */
	privacy_policy_url?: string | null;
	/**
	 * The URL of the terms and conditions for the business or organization.
	 * @nullable
	 */
	terms_and_conditions_url?: string | null;
	/**
	 * Indicates if the content is age gated.
	 * @nullable
	 */
	age_gated_content?: boolean | null;
	/**
	 * List of keywords that users can send to opt in or out of messages.
	 * @nullable
	 */
	opt_in_keywords?: string[] | null;
	/**
	 * A list of rejection reasons and codes describing why a Tollfree Verification has been rejected.
	 * @nullable
	 */
	rejection_reasons?: unknown[] | null;
	/** The URLs of the documents associated with the Tollfree Verification resource. */
	resource_links?: unknown | null;
	/**
	 * An optional external reference ID supplied by customer and echoed back on status retrieval.
	 * @nullable
	 */
	external_reference_id?: string | null;
	/**
	 * @maxLength 500
	 * @nullable
	 */
	vetting_id?: string | null;
	vetting_provider?: TollfreeVerificationEnumVettingProvider | null;
	/** @nullable */
	vetting_id_expiration?: string | null;
}
