/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1ServiceShortCode {
	/**
	 * The unique string that we created to identify the ShortCode resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^SC[0-9a-fA-F]{32}$
	 */
	sid?: string | null;
	/**
	 * The SID of the [Account](https://www.twilio.com/docs/iam/api/account) that created the ShortCode resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^AC[0-9a-fA-F]{32}$
	 */
	account_sid?: string | null;
	/**
	 * The SID of the [Service](https://www.twilio.com/docs/chat/rest/service-resource) the resource is associated with.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^MG[0-9a-fA-F]{32}$
	 */
	service_sid?: string | null;
	/**
	 * The date and time in GMT when the resource was created specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_created?: string | null;
	/**
	 * The date and time in GMT when the resource was last updated specified in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format.
	 * @nullable
	 */
	date_updated?: string | null;
	/**
	 * The [E.164](https://www.twilio.com/docs/glossary/what-e164) format of the short code.
	 * @nullable
	 */
	short_code?: string | null;
	/**
	 * The 2-character [ISO Country Code](https://www.iso.org/iso-3166-country-codes.html) of the number.
	 * @nullable
	 */
	country_code?: string | null;
	/**
	 * An array of values that describe whether the number can receive calls or messages. Can be: `SMS` and `MMS`.
	 * @nullable
	 */
	capabilities?: string[] | null;
	/**
	 * The absolute URL of the ShortCode resource.
	 * @nullable
	 */
	url?: string | null;
}
