/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export interface MessagingV1DomainDnsValidation {
	/**
	 * The unique string that we created to identify the Domain resource.
	 * @minLength 34
	 * @maxLength 34
	 * @nullable
	 * @pattern ^DN[0-9a-fA-F]{32}$
	 */
	domain_sid?: string | null;
	/** @nullable */
	is_valid?: boolean | null;
	/** @nullable */
	reason?: string | null;
	/** @nullable */
	url?: string | null;
}
