/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KeywordLocaleType } from "./keywordLocaleType";

export interface OptOutKeywordsEntity {
	keywordType: KeywordLocaleType;
	/** The message type identifier (typically country codes or special identifiers) */
	messageType: string;
	/**
	 * The keyword to add
	 * @minLength 1
	 * @maxLength 34
	 */
	keyword: string;
}
