/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { KeywordLocaleType } from './keywordLocaleType';

export interface OptOutMessagesEntity {
  keywordType: KeywordLocaleType;
  /** Message type (typically country code or region identifier) */
  messageType: string;
  /**
   * The message text content (max 320 characters)
   * @minLength 1
   * @maxLength 320
   */
  message: string;
}
