/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The current state of this User Conversation. One of `inactive`, `active` or `closed`.
 */
export type ParticipantConversationEnumState = typeof ParticipantConversationEnumState[keyof typeof ParticipantConversationEnumState];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ParticipantConversationEnumState = {
  inactive: 'inactive',
  active: 'active',
  closed: 'closed',
} as const;
