/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ReplayEnumPatchstatus =
	(typeof ReplayEnumPatchstatus)[keyof typeof ReplayEnumPatchstatus];

export const ReplayEnumPatchstatus = {
	cancelling: "cancelling",
} as const;
