/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ReplayEnumPatchstatus =
	(typeof ReplayEnumPatchstatus)[keyof typeof ReplayEnumPatchstatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReplayEnumPatchstatus = {
	cancelling: "cancelling",
} as const;
