/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ReplayEnumStatus =
	(typeof ReplayEnumStatus)[keyof typeof ReplayEnumStatus];

export const ReplayEnumStatus = {
	submitted: "submitted",
	starting: "starting",
	running: "running",
	cancelling: "cancelling",
	cancelled: "cancelled",
	failed: "failed",
	completed: "completed",
} as const;
