/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The HTTP method to be used when sending a webhook request. One of `GET` or `POST`.
 */
export type ServiceWebhookConfigurationEnumMethod =
	(typeof ServiceWebhookConfigurationEnumMethod)[keyof typeof ServiceWebhookConfigurationEnumMethod];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceWebhookConfigurationEnumMethod = {
	GET: "GET",
	POST: "POST",
} as const;
