/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of role. Can be: `conversation` for [Conversation](https://www.twilio.com/docs/conversations/api/conversation-resource) roles or `service` for [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) roles.
 */
export type ServiceRoleEnumRoleType =
	(typeof ServiceRoleEnumRoleType)[keyof typeof ServiceRoleEnumRoleType];

export const ServiceRoleEnumRoleType = {
	conversation: "conversation",
	service: "service",
} as const;
