/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The message delivery status, can be `read`, `failed`, `delivered`, `undelivered`, `sent` or null.
 */
export type ServiceConversationMessageReceiptEnumDeliveryStatus =
	(typeof ServiceConversationMessageReceiptEnumDeliveryStatus)[keyof typeof ServiceConversationMessageReceiptEnumDeliveryStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceConversationMessageReceiptEnumDeliveryStatus = {
	read: "read",
	failed: "failed",
	delivered: "delivered",
	undelivered: "undelivered",
	sent: "sent",
} as const;
