/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ServiceConversationMessageEnumOrderType =
	(typeof ServiceConversationMessageEnumOrderType)[keyof typeof ServiceConversationMessageEnumOrderType];

export const ServiceConversationMessageEnumOrderType = {
	asc: "asc",
	desc: "desc",
} as const;
