/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Source via which the request came from. Can be sdk, api.
 */
export type ServiceStatsConversationsRatelimitingerrorsEnumSource =
	(typeof ServiceStatsConversationsRatelimitingerrorsEnumSource)[keyof typeof ServiceStatsConversationsRatelimitingerrorsEnumSource];

export const ServiceStatsConversationsRatelimitingerrorsEnumSource = {
	SDK: "SDK",
	API: "API",
} as const;
