/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The target of this webhook: `webhook`, `studio`, `trigger`
 */
export type ServiceConversationScopedWebhookEnumTarget = typeof ServiceConversationScopedWebhookEnumTarget[keyof typeof ServiceConversationScopedWebhookEnumTarget];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceConversationScopedWebhookEnumTarget = {
  webhook: 'webhook',
  trigger: 'trigger',
  studio: 'studio',
} as const;
