/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Current state of this conversation. Can be either `initializing`, `active`, `inactive` or `closed` and defaults to `active`
 */
export type ServiceConversationEnumState =
	(typeof ServiceConversationEnumState)[keyof typeof ServiceConversationEnumState];

export const ServiceConversationEnumState = {
	inactive: "inactive",
	active: "active",
	closed: "closed",
	initializing: "initializing",
} as const;
