/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ServiceConversationParticipantEnumWebhookEnabledType =
	(typeof ServiceConversationParticipantEnumWebhookEnabledType)[keyof typeof ServiceConversationParticipantEnumWebhookEnabledType];

export const ServiceConversationParticipantEnumWebhookEnabledType = {
	true: "true",
	false: "false",
} as const;
