/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type ServiceConversationEnumWebhookEnabledType =
	(typeof ServiceConversationEnumWebhookEnabledType)[keyof typeof ServiceConversationEnumWebhookEnabledType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceConversationEnumWebhookEnabledType = {
	true: "true",
	false: "false",
} as const;
