/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Reserved.
 */
export type ServiceEnumScanMessageContent = typeof ServiceEnumScanMessageContent[keyof typeof ServiceEnumScanMessageContent];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceEnumScanMessageContent = {
  inherit: 'inherit',
  enable: 'enable',
  disable: 'disable',
} as const;
