/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Reserved.
 */
export type ServiceEnumScanMessageContent =
	(typeof ServiceEnumScanMessageContent)[keyof typeof ServiceEnumScanMessageContent];

export const ServiceEnumScanMessageContent = {
	inherit: "inherit",
	enable: "enable",
	disable: "disable",
} as const;
