/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The Status of this Sink. One of `initialized`, `validating`, `active` or `failed`.
 */
export type SinkEnumStatus =
	(typeof SinkEnumStatus)[keyof typeof SinkEnumStatus];

export const SinkEnumStatus = {
	initialized: "initialized",
	validating: "validating",
	active: "active",
	failed: "failed",
} as const;
