/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The Sink type. Can only be "kinesis" or "webhook" currently.
 */
export type SinkEnumSinkType =
	(typeof SinkEnumSinkType)[keyof typeof SinkEnumSinkType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SinkEnumSinkType = {
	kinesis: "kinesis",
	webhook: "webhook",
	segment: "segment",
	email: "email",
} as const;
