/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Source via which the request came from. Can be Twilsock.
 */
export type StatsTwilsockRatelimitingerrorsEnumSource =
	(typeof StatsTwilsockRatelimitingerrorsEnumSource)[keyof typeof StatsTwilsockRatelimitingerrorsEnumSource];

export const StatsTwilsockRatelimitingerrorsEnumSource = {
	TWILSOCK: "TWILSOCK",
} as const;
