/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { MessageTypeConfig } from './messageTypeConfig';

export interface SupportedMessageTypes {
  /** List of supported message types for opt-out configurations */
  message_types: MessageTypeConfig[];
}
