/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { TollfreeVerificationEnumUseCaseCategoriesItem } from "./tollfreeVerificationEnumUseCaseCategoriesItem";

/**
 * The category of the use case for the Tollfree Number. List as many as are applicable.
 * @nullable
 */
export type TollfreeVerificationEnumUseCaseCategories =
	| TollfreeVerificationEnumUseCaseCategoriesItem[]
	| null;
