/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * Describe how a user opts-in to text messages.
 */
export type TollfreeVerificationEnumOptInType = typeof TollfreeVerificationEnumOptInType[keyof typeof TollfreeVerificationEnumOptInType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TollfreeVerificationEnumOptInType = {
  VERBAL: 'VERBAL',
  WEB_FORM: 'WEB_FORM',
  PAPER_FORM: 'PAPER_FORM',
  VIA_TEXT: 'VIA_TEXT',
  MOBILE_QR_CODE: 'MOBILE_QR_CODE',
  IMPORT: 'IMPORT',
  IMPORT_PLEASE_REPLACE: 'IMPORT_PLEASE_REPLACE',
} as const;
