/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The organizational authority for business registrations. Required for all business types except SOLE_PROPRIETOR.
 * @nullable
 */
export type TollfreeVerificationEnumBusinessRegistrationAuthority =
	| (typeof TollfreeVerificationEnumBusinessRegistrationAuthority)[keyof typeof TollfreeVerificationEnumBusinessRegistrationAuthority]
	| null;

export const TollfreeVerificationEnumBusinessRegistrationAuthority = {
	EIN: "EIN",
	CBN: "CBN",
	CRN: "CRN",
	PROVINCIAL_NUMBER: "PROVINCIAL_NUMBER",
	VAT: "VAT",
	ACN: "ACN",
	ABN: "ABN",
	BRN: "BRN",
	SIREN: "SIREN",
	SIRET: "SIRET",
	NZBN: "NZBN",
	"USt-IdNr": "USt-IdNr",
	CIF: "CIF",
	NIF: "NIF",
	CNPJ: "CNPJ",
	UID: "UID",
	NEQ: "NEQ",
	OTHER: "OTHER",
} as const;
