/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The type of business, valid values are PRIVATE_PROFIT, PUBLIC_PROFIT, NON_PROFIT, SOLE_PROPRIETOR, GOVERNMENT. Required field.
 * @nullable
 */
export type TollfreeVerificationEnumBusinessType =
	| (typeof TollfreeVerificationEnumBusinessType)[keyof typeof TollfreeVerificationEnumBusinessType]
	| null;

export const TollfreeVerificationEnumBusinessType = {
	PRIVATE_PROFIT: "PRIVATE_PROFIT",
	PUBLIC_PROFIT: "PUBLIC_PROFIT",
	SOLE_PROPRIETOR: "SOLE_PROPRIETOR",
	NON_PROFIT: "NON_PROFIT",
	GOVERNMENT: "GOVERNMENT",
} as const;
