/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The third-party political vetting provider.
 * @nullable
 */
export type TollfreeVerificationEnumVettingProvider =
	| (typeof TollfreeVerificationEnumVettingProvider)[keyof typeof TollfreeVerificationEnumVettingProvider]
	| null;

export const TollfreeVerificationEnumVettingProvider = {
	CAMPAIGN_VERIFY: "CAMPAIGN_VERIFY",
} as const;
