/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSinkBody = {
	/** A human readable description for the Sink **This value should not contain PII.** */
	Description: string;
};
