/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The HTTP method we should use to call `inbound_request_url`. Can be `GET` or `POST` and the default is `POST`.
 */
export type UpdateServiceBodyInboundMethod =
	(typeof UpdateServiceBodyInboundMethod)[keyof typeof UpdateServiceBodyInboundMethod];

export const UpdateServiceBodyInboundMethod = {
	GET: "GET",
	POST: "POST",
} as const;
