/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Accounts
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateCredentialPublicKeyBody = {
	/** A descriptive string that you create to describe the resource. It can be up to 64 characters long. */
	FriendlyName?: string;
};
