/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Events
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateSubscriptionBody = {
  /** A human readable description for the Subscription. */
  Description?: string;
};
