/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { ConfigurationWebhookEnumTarget } from './configurationWebhookEnumTarget';

export type UpdateConfigurationWebhookBody = {
  /** The HTTP method to be used when sending a webhook request. */
  Method?: string;
  /** The list of webhook event triggers that are enabled for this Service: `onMessageAdded`, `onMessageUpdated`, `onMessageRemoved`, `onMessageAdd`, `onMessageUpdate`, `onMessageRemove`, `onConversationUpdated`, `onConversationRemoved`, `onConversationAdd`, `onConversationAdded`, `onConversationRemove`, `onConversationUpdate`, `onConversationStateUpdated`, `onParticipantAdded`, `onParticipantUpdated`, `onParticipantRemoved`, `onParticipantAdd`, `onParticipantRemove`, `onParticipantUpdate`, `onDeliveryUpdated`, `onUserAdded`, `onUserUpdate`, `onUserUpdated` */
  Filters?: string[];
  /** The absolute url the pre-event webhook request should be sent to. */
  PreWebhookUrl?: string;
  /** The absolute url the post-event webhook request should be sent to. */
  PostWebhookUrl?: string;
  Target?: ConfigurationWebhookEnumTarget;
};
