/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */
import type { UserConversationEnumNotificationLevel } from "./userConversationEnumNotificationLevel";

export type UpdateUserConversationBody = {
	NotificationLevel?: UserConversationEnumNotificationLevel;
	/** The date of the last message read in conversation by the user, given in ISO 8601 format. */
	LastReadTimestamp?: string;
	/**
	 * The index of the last Message in the Conversation that the Participant has read.
	 * @nullable
	 */
	LastReadMessageIndex?: number | null;
};
