/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

export type UpdateConfigurationBody = {
	/**
	 * The SID of the default [Conversation Service](https://www.twilio.com/docs/conversations/api/service-resource) to use when creating a conversation.
	 * @minLength 34
	 * @maxLength 34
	 * @pattern ^IS[0-9a-fA-F]{32}$
	 */
	DefaultChatServiceSid?: string;
	/**
	 * The SID of the default [Messaging Service](https://www.twilio.com/docs/messaging/api/service-resource) to use when creating a conversation.
	 * @minLength 34
	 * @maxLength 34
	 * @pattern ^MG[0-9a-fA-F]{32}$
	 */
	DefaultMessagingServiceSid?: string;
	/** Default ISO8601 duration when conversation will be switched to `inactive` state. Minimum value for this timer is 1 minute. */
	DefaultInactiveTimer?: string;
	/** Default ISO8601 duration when conversation will be switched to `closed` state. Minimum value for this timer is 10 minutes. */
	DefaultClosedTimer?: string;
};
