/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The Notification Level of this User Conversation. One of `default` or `muted`.
 */
export type UserConversationEnumNotificationLevel =
	(typeof UserConversationEnumNotificationLevel)[keyof typeof UserConversationEnumNotificationLevel];

export const UserConversationEnumNotificationLevel = {
	default: "default",
	muted: "muted",
} as const;
