/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Twilio - Conversations
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The Notification Level of this User Conversation. One of `default` or `muted`.
 */
export type UserConversationEnumNotificationLevel =
	(typeof UserConversationEnumNotificationLevel)[keyof typeof UserConversationEnumNotificationLevel];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserConversationEnumNotificationLevel = {
	default: "default",
	muted: "muted",
} as const;
