/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Twilio - Messaging
 * This is the public Twilio REST API.
 * OpenAPI spec version: 1.0.0
 */

/**
 * The version of the Messaging API to use for this request
 */
export type XTwilioApiVersionParameter = string;
