export const ADMIN_USER_IDS: string[] = [
	"ZvUmzplbR8KA82sSPom7UmkrgTM9XtXp", // ytwater Dev
	"vtpk6yV3s0xpTafnEJEC2IA8DKJHBzjd", // ytwater Prod
] as const;
export const MAIN_CONVERSATION_UNIQUE_NAME = "main" as const;
export const TWILIO_WHATSAPP_NUMBER = "+18589520996" as const;
export const TWILIO_WHATSAPP_OTP_TEMPLATE_SID =
	"HX9b5f7b983db5c8777ee84ea09fbd7de1" as const;

export const SURFLINE_TORREY_PINES_SPOT_ID =
	"584204204e65fad6a7709994" as const;

export const VALID_WHATSAPP_INCOMING_NUMBERS = [
	"whatsapp:+16198064334",
] as const;

export const REQUIRED_ENV_VARS = [
	"OPENAI_API_KEY",
	"DEEPSEEK_API_KEY",
	"CLOUDFLARE_API_TOKEN",
	"GEMINI_API_KEY",
	"BETTER_AUTH_SECRET",
	"GOOGLE_CLIENT_SECRET",
	"VAPID_PUBLIC_KEY",
	"VAPID_PRIVATE_KEY",
	"SWELL_CLOUD_API_KEY",
	"TWILIO_ACCOUNT_SID",
	"TWILIO_API_KEY",
	"TWILIO_API_SECRET",
	"TWILIO_AUTH_TOKEN",
	"TWILIO_SERVICE_SID",
	"TWILIO_EVENT_SYNC_ID_DEV",
	"TWILIO_EVENT_SYNC_ID_PROD",
] as const;

export const TORREY_PILES_LAT_LNG = {
	lat: 32.927,
	lng: -117.26,
} as const;
