/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Swellcloud API
 * OpenAPI spec version: 1.0.0
 */

export type GetChartV1ChartsVariableForecastHourGetParams = {
/**
 * Image format: png or svg
 */
format?: string;
};
