/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Swellcloud API
 * OpenAPI spec version: 1.0.0
 */
import type { ValidationError } from './validationError';

export interface HTTPValidationError {
  detail?: ValidationError[];
}
