/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Swellcloud API
 * OpenAPI spec version: 1.0.0
 */

export type WmtsProxyV1WmtsProxyZXYGetParams = {
	/**
	 * Layer identifier (VHM0_SW1, VHM0_SW2, VHM0)
	 */
	layer?: string;
	/**
	 * Time in ISO8601 format
	 */
	time: string;
};
