/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * WAHA - WhatsApp HTTP API
 * <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href="/dashboard"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href="https://waha.devlike.pro/" target="_blank">Documentation</a></li><li><a href="https://waha.devlike.pro/docs/how-to/engines/#features" target="_blank">Supported features in engines</a></li><li><a href="https://github.com/devlikeapro/waha" target="_blank">GitHub - WAHA Core</a></li><li><a href="https://github.com/devlikeapro/waha-plus" target="_blank">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href="https://waha.devlike.pro/docs/how-to/plus-version/" target="_blank">WAHA Plus</a></li><li><a href="https://patreon.com/wa_http_api/" target="_blank">Patreon</a></li><li><a href="https://boosty.to/wa-http-api/" target="_blank">Boosty</a></li><li><a href="https://portal.devlike.pro/" target="_blank">Patron Portal</a></li></ul>
 * OpenAPI spec version: 2026.1.5
 */
import type { _GroupV2ParticipantsEventData } from "./_groupV2ParticipantsEventData";
import type { GroupId } from "./groupId";
import type { GroupParticipant } from "./groupParticipant";
import type { GroupV2ParticipantsEventType } from "./groupV2ParticipantsEventType";

export interface GroupV2ParticipantsEvent {
	/** Type of the event */
	type: GroupV2ParticipantsEventType;
	/** Unix timestamp */
	timestamp: number;
	group: GroupId;
	participants: GroupParticipant[];
	_data: _GroupV2ParticipantsEventData;
}
