/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * WAHA - WhatsApp HTTP API
 * <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href="/dashboard"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href="https://waha.devlike.pro/" target="_blank">Documentation</a></li><li><a href="https://waha.devlike.pro/docs/how-to/engines/#features" target="_blank">Supported features in engines</a></li><li><a href="https://github.com/devlikeapro/waha" target="_blank">GitHub - WAHA Core</a></li><li><a href="https://github.com/devlikeapro/waha-plus" target="_blank">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href="https://waha.devlike.pro/docs/how-to/plus-version/" target="_blank">WAHA Plus</a></li><li><a href="https://patreon.com/wa_http_api/" target="_blank">Patreon</a></li><li><a href="https://boosty.to/wa-http-api/" target="_blank">Boosty</a></li><li><a href="https://portal.devlike.pro/" target="_blank">Patron Portal</a></li></ul>
 * OpenAPI spec version: 2026.1.5
 */
import type { LabelChatAssociation } from "./labelChatAssociation";
import type { MeInfo } from "./meInfo";
import type { WAHAEnvironment } from "./wAHAEnvironment";
import type { WAHAWebhookLabelChatAddedEngine } from "./wAHAWebhookLabelChatAddedEngine";
import type { WAHAWebhookLabelChatAddedEvent } from "./wAHAWebhookLabelChatAddedEvent";
import type { WAHAWebhookLabelChatAddedMetadata } from "./wAHAWebhookLabelChatAddedMetadata";

export interface WAHAWebhookLabelChatAdded {
	/** Unique identifier for the event - lower case ULID format. https://github.com/ulid/spec */
	id: string;
	/** Unix timestamp (ms) for when the event was created. */
	timestamp: number;
	session: string;
	/** Metadata for the session. */
	metadata?: WAHAWebhookLabelChatAddedMetadata;
	engine: WAHAWebhookLabelChatAddedEngine;
	/** The event is triggered when a label is added to a chat */
	event: WAHAWebhookLabelChatAddedEvent;
	payload: LabelChatAssociation;
	me?: MeInfo;
	environment: WAHAEnvironment;
}
