/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * WAHA - WhatsApp HTTP API
 * <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href="/dashboard"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href="https://waha.devlike.pro/" target="_blank">Documentation</a></li><li><a href="https://waha.devlike.pro/docs/how-to/engines/#features" target="_blank">Supported features in engines</a></li><li><a href="https://github.com/devlikeapro/waha" target="_blank">GitHub - WAHA Core</a></li><li><a href="https://github.com/devlikeapro/waha-plus" target="_blank">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href="https://waha.devlike.pro/docs/how-to/plus-version/" target="_blank">WAHA Plus</a></li><li><a href="https://patreon.com/wa_http_api/" target="_blank">Patreon</a></li><li><a href="https://boosty.to/wa-http-api/" target="_blank">Boosty</a></li><li><a href="https://portal.devlike.pro/" target="_blank">Patron Portal</a></li></ul>
 * OpenAPI spec version: 2026.1.5
 */

/**
 * The event is triggered when a user reacts or removes a reaction.
 */
export type WAHAWebhookMessageReactionEvent =
	(typeof WAHAWebhookMessageReactionEvent)[keyof typeof WAHAWebhookMessageReactionEvent];

export const WAHAWebhookMessageReactionEvent = {
	sessionstatus: "session.status",
	message: "message",
	messagereaction: "message.reaction",
	messageany: "message.any",
	messageack: "message.ack",
	messageackgroup: "message.ack.group",
	messagewaiting: "message.waiting",
	messagerevoked: "message.revoked",
	messageedited: "message.edited",
	statechange: "state.change",
	groupjoin: "group.join",
	groupleave: "group.leave",
	groupv2join: "group.v2.join",
	groupv2leave: "group.v2.leave",
	groupv2update: "group.v2.update",
	groupv2participants: "group.v2.participants",
	presenceupdate: "presence.update",
	pollvote: "poll.vote",
	pollvotefailed: "poll.vote.failed",
	chatarchive: "chat.archive",
	callreceived: "call.received",
	callaccepted: "call.accepted",
	callrejected: "call.rejected",
	labelupsert: "label.upsert",
	labeldeleted: "label.deleted",
	labelchatadded: "label.chat.added",
	labelchatdeleted: "label.chat.deleted",
	eventresponse: "event.response",
	eventresponsefailed: "event.response.failed",
	engineevent: "engine.event",
} as const;
