/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * WAHA - WhatsApp HTTP API
 * <b>WhatsApp HTTP API</b> that you can run in a click!<br/><a href="/dashboard"><b>📊 Dashboard</b></a><br/><br/>Learn more:<ul><li><a href="https://waha.devlike.pro/" target="_blank">Documentation</a></li><li><a href="https://waha.devlike.pro/docs/how-to/engines/#features" target="_blank">Supported features in engines</a></li><li><a href="https://github.com/devlikeapro/waha" target="_blank">GitHub - WAHA Core</a></li><li><a href="https://github.com/devlikeapro/waha-plus" target="_blank">GitHub - WAHA Plus</a></li></ul><p>Support the project and get WAHA Plus version!</p><ul><li><a href="https://waha.devlike.pro/docs/how-to/plus-version/" target="_blank">WAHA Plus</a></li><li><a href="https://patreon.com/wa_http_api/" target="_blank">Patreon</a></li><li><a href="https://boosty.to/wa-http-api/" target="_blank">Boosty</a></li><li><a href="https://portal.devlike.pro/" target="_blank">Patron Portal</a></li></ul>
 * OpenAPI spec version: 2026.1.5
 */
import type { WAMessageReactionSource } from "./wAMessageReactionSource";
import type { WAReaction } from "./wAReaction";

export interface WAMessageReaction {
	/** Message ID */
	id: string;
	/** Unix timestamp for when the message was created */
	timestamp: number;
	/** ID for the Chat that this message was sent to, except if the message was sent by the current user  */
	from: string;
	/** Indicates if the message was sent by the current user */
	fromMe: boolean;
	/** The device that sent the message - either API or APP. Available in events (webhooks/websockets) only and only "fromMe: true" messages. */
	source: WAMessageReactionSource;
	/**
	 * ID for who this message is for.
	 * If the message is sent by the current user, it will be the Chat to which the message is being sent.
	 * If the message is sent by another user, it will be the ID for the current user.
	 */
	to: string;
	/** For groups - participant who sent the message */
	participant: string;
	/** Reaction to the message. Either the reaction (emoji) or empty string to remove the reaction */
	reaction: WAReaction;
}
